force-app/main/default/objects/National_Outings_Trip__c/National_Outings_Trip__c.object-meta.xml
<CustomObject>
    <label>National Outings Trip</label>
    <nameField>
        <label>National Outings Trip Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>National Outings Trips</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/National_Outings_Trip_Vendor__c/National_Outings_Trip_Vendor__c.object-meta.xml
<CustomObject>
    <label>National Outings Trip Vendor</label>
    <nameField>
        <displayFormat>NOV-{00000000}</displayFormat>
        <label>National Outings Trip Vendor Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>National Outings Trip Vendors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/National_Outings_Trip_Vendor__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>National Outings Trip Vendors</relationshipLabel>
    <relationshipName>National_Outings_Trip_Vendors</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/National_Outings_Trip_Vendor__c/fields/National_Outings_Trip__c.field-meta.xml
<CustomField>
    <fullName>National_Outings_Trip__c</fullName>
    <label>National Outings Trip</label>
    <referenceTo>National_Outings_Trip__c</referenceTo>
    <relationshipLabel>National Outings Trip Vendors</relationshipLabel>
    <relationshipName>National_Outings_Trip_Vendors</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/NatoutTripVendorExportController.cls
public with sharing class NatoutTripVendorExportController {
    public NatoutTripVendorExportController() {

    }
    public List<ExportRow> getExportList() {
        String idParameterString = ApexPages.currentPage().getParameters().get('trips');
        List<String> tripIdList = idParameterString.split(',');
        List<ExportRow> rowList = new List<ExportRow>();
        for(National_Outings_Trip_Vendor__c vendor : [
            SELECT 
                National_Outings_Trip__c,
                Type__c,
                Account__r.Name
            FROM National_Outings_Trip_Vendor__c
            WHERE National_Outings_Trip__c IN :tripIdList
            ]
        ) {
            rowList.add(
                new ExportRow(
                    vendor.National_Outings_Trip__c,
                    vendor.Type__c,
                    vendor.Account__r.Name
                )
            );
        }
        return rowList;
    }
    public Class ExportRow {
        public ExportRow(String tripId, String type, String name) {
            this.tripId = tripId;
            this.type = type;
            this.name = name;
        }
        public String tripId {get; set;}
        public String type {get; set;}
        public String name {get; set;}
    }
}