force-app/main/default/objects/National_Outings_Trip__c/National_Outings_Trip__c.object-meta.xml
<CustomObject>
    <label>National Outings Trip</label>
    <nameField>
        <label>National Outings Trip Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>National Outings Trips</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/National_Outings_Trip_Link__c/National_Outings_Trip_Link__c.object-meta.xml
<CustomObject>
    <label>National Outings Trip Link</label>
    <nameField>
        <displayFormat>TL-{00000000}</displayFormat>
        <label>National Outings Trip Link Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>National Outings Trip Links</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/National_Outings_Trip_Link__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/National_Outings_Trip_Link__c/fields/National_Outings_Trip__c.field-meta.xml
<CustomField>
    <fullName>National_Outings_Trip__c</fullName>
    <label>National Outings Trip</label>
    <referenceTo>National_Outings_Trip__c</referenceTo>
    <relationshipLabel>National Outings Trip Links</relationshipLabel>
    <relationshipName>National_Outings_Trip_Links</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/NatoutTripLinksController.cls
public with sharing class NatoutTripLinksController {
    @AuraEnabled (cacheable=true)
    public static List<National_Outings_Trip_Link__c> getLinkList(String tripId) {
        List<National_Outings_Trip_Link__c> linkList = [
            SELECT Id, Url__c, Description__c
            FROM National_Outings_Trip_Link__c
            WHERE National_Outings_Trip__c = :tripId
            ORDER BY CreatedDate
        ];
        return linkList;
    }
}