force-app/main/default/objects/National_Outings_Trip__c/National_Outings_Trip__c.object-meta.xml
<CustomObject>
    <label>National Outings Trip</label>
    <nameField>
        <label>National Outings Trip Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>National Outings Trips</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/National_Outings_Trip__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/National_Outings_Trip__c/fields/Subcommittee__c.field-meta.xml
<CustomField>
    <fullName>Subcommittee__c</fullName>
    <label>Subcommittee</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/National_Outings_Trip_Budget_Item__c/National_Outings_Trip_Budget_Item__c.object-meta.xml
<CustomObject>
    <label>National Outings Trip Budget Item</label>
    <nameField>
        <displayFormat>TI-{00000000}</displayFormat>
        <label>National Outings Trip Budget Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>National Outings Trip Budget Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/National_Outings_Trip_Budget_Item__c/fields/Budget_Category__c.field-meta.xml
<CustomField>
    <fullName>Budget_Category__c</fullName>
    <label>Budget Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Meals</fullName>
            </value>
            <value>
                <fullName>Volunteer Travel</fullName>
            </value>
            <value>
                <fullName>Concessionaires</fullName>
            </value>
            <value>
                <fullName>Transportation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/National_Outings_Trip_Budget_Item__c/fields/National_Outings_Trip__c.field-meta.xml
<CustomField>
    <fullName>National_Outings_Trip__c</fullName>
    <label>National Outings Trip</label>
    <referenceTo>National_Outings_Trip__c</referenceTo>
    <relationshipLabel>National Outings Trip Budget Items</relationshipLabel>
    <relationshipName>National_Outings_Trip_Budget_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/NatoutTripBudgetControllerTest.cls
@isTest
public with sharing class NatoutTripBudgetControllerTest {
    static testMethod void myUnitTest() {
        National_Outings_Trip__c trip = new National_Outings_Trip__c(
            Name = 'Test Trip',
            Subcommittee__c = 'Knapsack',
            Start_Date__c = Date.today(),
            End_Date__c = Date.today() + 2
        );
        insert trip;
        
        National_Outings_Trip_Budget_Item__c item = new National_Outings_Trip_Budget_Item__c(
            National_Outings_Trip__c = trip.Id,
            Budget_Category__c = 'Volunteer Travel',
            Amount__c = 10
        );
        insert item;
        List<National_Outings_Trip_Budget_Item__c> volTravList = NatoutTripBudgetController.getVolTravelList(trip.Id);
        System.assertEquals(1, volTravList.size());

        item = new National_Outings_Trip_Budget_Item__c(
            National_Outings_Trip__c = trip.Id,
            Budget_Category__c = 'Meals',
            Amount__c = 10
        );
        insert item;    
        List<National_Outings_Trip_Budget_Item__c> mealsList = NatoutTripBudgetController.getMealsList(trip.Id);
        System.assertEquals(1, mealsList.size());

        item = new National_Outings_Trip_Budget_Item__c(
            National_Outings_Trip__c = trip.Id,
            Budget_Category__c = 'Transportation',
            Amount__c = 10
        );
        insert item;    
        List<National_Outings_Trip_Budget_Item__c> transportList = NatoutTripBudgetController.getTransportationList(trip.Id);
        System.assertEquals(1, transportList.size());

        item = new National_Outings_Trip_Budget_Item__c(
            National_Outings_Trip__c = trip.Id,
            Budget_Category__c = 'Concessionaires',
            Amount__c = 10
        );
        insert item;    
        List<National_Outings_Trip_Budget_Item__c> concessList = NatoutTripBudgetController.getConcessionaireList(trip.Id);
        System.assertEquals(1, concessList.size());
    }
}