force-app/main/default/objects/National_Outings_Trip__c/National_Outings_Trip__c.object-meta.xml
<CustomObject>
    <label>National Outings Trip</label>
    <nameField>
        <label>National Outings Trip Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>National Outings Trips</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/National_Outings_Trip__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/National_Outings_Trip__c/fields/Subcommittee__c.field-meta.xml
<CustomField>
    <fullName>Subcommittee__c</fullName>
    <label>Subcommittee</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/National_Outings_Trip_Itinerary__c/National_Outings_Trip_Itinerary__c.object-meta.xml
<CustomObject>
    <label>National Outings Trip Itinerary</label>
    <nameField>
        <displayFormat>TI-{00000000}</displayFormat>
        <label>National Outings Trip Itinerary Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>National Outings Trip Itineraries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/National_Outings_Trip_Itinerary__c/fields/Day_Number__c.field-meta.xml
<CustomField>
    <fullName>Day_Number__c</fullName>
    <label>Day Number</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/National_Outings_Trip_Itinerary__c/fields/National_Outings_Trip__c.field-meta.xml
<CustomField>
    <fullName>National_Outings_Trip__c</fullName>
    <label>National Outings Trip</label>
    <referenceTo>National_Outings_Trip__c</referenceTo>
    <relationshipLabel>National Outings Trip Itineraries</relationshipLabel>
    <relationshipName>National_Outings_Trip_Itineraries</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/NatoutTripItineraryControllerTest.cls
@isTest
public with sharing class NatoutTripItineraryControllerTest {
    static testMethod void myUnitTest() {
        National_Outings_Trip__c trip = new National_Outings_Trip__c(
            Name = 'Test Trip',
            Subcommittee__c = 'Knapsack',
            Start_Date__c = Date.today(),
            End_Date__c = Date.today() + 2
        );
        insert trip;
     
        National_Outings_Trip_Itinerary__c itinerary = new National_Outings_Trip_Itinerary__c(
            National_Outings_Trip__c = trip.Id,
            Day_Number__c = 1
        );
        insert itinerary;
        List<National_Outings_Trip_Itinerary__c> itineraryList = NatoutTripItineraryController.getItineraryList(trip.Id);
        System.assertEquals(1, itineraryList.size());

        NatoutTripItineraryController ctl = new NatoutTripItineraryController();
        PageReference pageRef = Page.NatoutTripItineraryReport;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('id', trip.Id);
        List<NatoutTripItineraryController.PrintReport> reportList = ctl.getReportList();
    }
}