force-app/main/default/objects/National_Outings_Trip__c/National_Outings_Trip__c.object-meta.xml
<CustomObject>
    <label>National Outings Trip</label>
    <nameField>
        <label>National Outings Trip Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>National Outings Trips</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/National_Outings_Trip__c/fields/Budget_Approved_By__c.field-meta.xml
<CustomField>
    <fullName>Budget_Approved_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Budget Approved By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>National_Outings_Trips</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/National_Outings_Trip__c/fields/Budget_Approved_Date__c.field-meta.xml
<CustomField>
    <fullName>Budget_Approved_Date__c</fullName>
    <label>Budget Approved Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/National_Outings_Trip__c/fields/Date_Last_Returned__c.field-meta.xml
<CustomField>
    <fullName>Date_Last_Returned__c</fullName>
    <label>Date Last Returned</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/National_Outings_Trip__c/fields/Date_Last_Submitted__c.field-meta.xml
<CustomField>
    <fullName>Date_Last_Submitted__c</fullName>
    <label>Date Last Submitted</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/National_Outings_Trip__c/fields/Date_Returned__c.field-meta.xml
<CustomField>
    <fullName>Date_Returned__c</fullName>
    <label>Date Returned</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/National_Outings_Trip__c/fields/Date_Submitted__c.field-meta.xml
<CustomField>
    <fullName>Date_Submitted__c</fullName>
    <label>Date_Submitted</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/National_Outings_Trip__c/fields/First_Time_Run__c.field-meta.xml
<CustomField>
    <fullName>First_Time_Run__c</fullName>
    <defaultValue>true</defaultValue>
    <label>First Time Run</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/National_Outings_Trip__c/fields/Prior_Trip__c.field-meta.xml
<CustomField>
    <fullName>Prior_Trip__c</fullName>
    <label>Prior Trip #</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/National_Outings_Trip__c/fields/Prior_Trip_Price__c.field-meta.xml
<CustomField>
    <fullName>Prior_Trip_Price__c</fullName>
    <label>Prior Trip Price</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/National_Outings_Trip__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&apos;Started&apos;</defaultValue>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Started</fullName>
                <default>true</default>
                <label>Started</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Returned</fullName>
            </value>
            <value>
                <fullName>Approved by Chair</fullName>
            </value>
            <value>
                <fullName>Approved by Staff</fullName>
            </value>
            <value>
                <fullName>Uploaded to TRAIL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/National_Outings_Trip_Agency__c/National_Outings_Trip_Agency__c.object-meta.xml
<CustomObject>
    <label>National Outings Trip Agency</label>
    <nameField>
        <displayFormat>TA-{00000000}</displayFormat>
        <label>National Outings Trip Agency Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>National Outings Trip Agencies</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/National_Outings_Trip_Agency__c/fields/National_Outings_Trip__c.field-meta.xml
<CustomField>
    <fullName>National_Outings_Trip__c</fullName>
    <label>National Outings Trip</label>
    <referenceTo>National_Outings_Trip__c</referenceTo>
    <relationshipLabel>National Outings Trip Agencies</relationshipLabel>
    <relationshipName>National_Outings_Trip_Agencies</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/National_Outings_Trip_Budget_Item__c/National_Outings_Trip_Budget_Item__c.object-meta.xml
<CustomObject>
    <label>National Outings Trip Budget Item</label>
    <nameField>
        <displayFormat>TI-{00000000}</displayFormat>
        <label>National Outings Trip Budget Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>National Outings Trip Budget Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/National_Outings_Trip_Budget_Item__c/fields/National_Outings_Trip__c.field-meta.xml
<CustomField>
    <fullName>National_Outings_Trip__c</fullName>
    <label>National Outings Trip</label>
    <referenceTo>National_Outings_Trip__c</referenceTo>
    <relationshipLabel>National Outings Trip Budget Items</relationshipLabel>
    <relationshipName>National_Outings_Trip_Budget_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/National_Outings_Trip_Itinerary__c/National_Outings_Trip_Itinerary__c.object-meta.xml
<CustomObject>
    <label>National Outings Trip Itinerary</label>
    <nameField>
        <displayFormat>TI-{00000000}</displayFormat>
        <label>National Outings Trip Itinerary Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>National Outings Trip Itineraries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/National_Outings_Trip_Itinerary__c/fields/National_Outings_Trip__c.field-meta.xml
<CustomField>
    <fullName>National_Outings_Trip__c</fullName>
    <label>National Outings Trip</label>
    <referenceTo>National_Outings_Trip__c</referenceTo>
    <relationshipLabel>National Outings Trip Itineraries</relationshipLabel>
    <relationshipName>National_Outings_Trip_Itineraries</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/National_Outings_Trip_Staff__c/National_Outings_Trip_Staff__c.object-meta.xml
<CustomObject>
    <label>National Outings Trip Staff</label>
    <nameField>
        <displayFormat>TS-{00000000}</displayFormat>
        <label>National Outing Trip Staff Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>National Outings Trip Staffs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/National_Outings_Trip_Staff__c/fields/National_Outings_Trip__c.field-meta.xml
<CustomField>
    <fullName>National_Outings_Trip__c</fullName>
    <label>National Outings Trip</label>
    <referenceTo>National_Outings_Trip__c</referenceTo>
    <relationshipLabel>National Outings Trip Staffs</relationshipLabel>
    <relationshipName>National_Outings_Trip_Staffs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/National_Outings_Trip_Staff__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Assistant Commissary</fullName>
            </value>
            <value>
                <fullName>Assistant_Leader</fullName>
                <label>Assistant-Leader</label>
            </value>
            <value>
                <fullName>Assistant-Leader 2</fullName>
            </value>
            <value>
                <fullName>Assistant Leader 3</fullName>
            </value>
            <value>
                <fullName>Assistant Leader 4</fullName>
            </value>
            <value>
                <fullName>Assistant Trainee</fullName>
            </value>
            <value>
                <fullName>Associate Leader</fullName>
            </value>
            <value>
                <fullName>Board Liaison</fullName>
            </value>
            <value>
                <fullName>Co-Leader</fullName>
            </value>
            <value>
                <fullName>Commissary</fullName>
            </value>
            <value>
                <fullName>Conservation Coordinator</fullName>
            </value>
            <value>
                <fullName>Conservation Specialist</fullName>
            </value>
            <value>
                <fullName>Cook</fullName>
            </value>
            <value>
                <fullName>Crew</fullName>
            </value>
            <value>
                <fullName>Doctor</fullName>
            </value>
            <value>
                <fullName>Evaluation Coordinator</fullName>
            </value>
            <value>
                <fullName>Guide</fullName>
            </value>
            <value>
                <fullName>Home School Mentor</fullName>
            </value>
            <value>
                <fullName>Host</fullName>
            </value>
            <value>
                <fullName>Instructor</fullName>
            </value>
            <value>
                <fullName>Leader</fullName>
            </value>
            <value>
                <fullName>Leader Child</fullName>
            </value>
            <value>
                <fullName>Liaison</fullName>
            </value>
            <value>
                <fullName>Mentor Leader</fullName>
            </value>
            <value>
                <fullName>Mountaineering Specialist</fullName>
            </value>
            <value>
                <fullName>Naturalist</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Specialist</fullName>
            </value>
            <value>
                <fullName>Support Staff</fullName>
            </value>
            <value>
                <fullName>Trainee</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/National_Outings_Trip_Vendor__c/National_Outings_Trip_Vendor__c.object-meta.xml
<CustomObject>
    <label>National Outings Trip Vendor</label>
    <nameField>
        <displayFormat>NOV-{00000000}</displayFormat>
        <label>National Outings Trip Vendor Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>National Outings Trip Vendors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/National_Outings_Trip_Vendor__c/fields/National_Outings_Trip__c.field-meta.xml
<CustomField>
    <fullName>National_Outings_Trip__c</fullName>
    <label>National Outings Trip</label>
    <referenceTo>National_Outings_Trip__c</referenceTo>
    <relationshipLabel>National Outings Trip Vendors</relationshipLabel>
    <relationshipName>National_Outings_Trip_Vendors</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/NatoutTripCopy.cls
public without sharing class NatoutTripCopy {
    @AuraEnabled
    public static String copy(String tripId) {
        String retVal = null;
        String query = 'SELECT ' + 
            getFieldList('National_Outings_Trip__c') +
            ' FROM National_Outings_Trip__c WHERE Id = :tripId';
        National_Outings_Trip__c fromTrip = Database.query(query);
        National_Outings_Trip__c toTrip = fromTrip.clone(false, true, false, false);
        toTrip.Status__c = 'Started';
        toTrip.Date_Submitted__c = null;
        toTrip.Date_Last_Submitted__c = null;
        toTrip.Date_Returned__c = null;
        toTrip.Date_Last_Returned__c = null;
        toTrip.Name = 'Copy of ' + fromTrip.Name;
        toTrip.OwnerID = UserInfo.getUserId();
        toTrip.Budget_Approved_By__c = null;
        toTrip.Budget_Approved_Date__c = null;
        toTrip.Brochure_Submitted_Date__c = null;
        if(
            toTrip.First_Time_Run__c == false &&
            toTrip.Prior_Trip__c != null &&
            toTrip.Prior_Trip_Price__c == null
        ) {
            toTrip.Prior_Trip_Price__c = NatoutTripService.getTripPrice(toTrip.Prior_Trip__c);
        } 
        Database.SaveResult rslt = Database.insert(toTrip);
        if( ! rslt.isSuccess()) {
            return null;
        }
        retVal = rslt.getId();

        List<SObject> relObjList = new List<SObject>();
        relObjList.addAll(getRelatedObjList('National_Outings_Trip_Budget_Item__c', tripId, retVal));
        relObjList.addAll(getRelatedObjList('National_Outings_Trip_Agency__c', tripId, retVal));
        relObjList.addAll(getRelatedObjList('National_Outings_Trip_Itinerary__c', tripId, retVal));
        relObjList.addAll(getRelatedObjList('National_Outings_Trip_Vendor__c', tripId, retVal));

        List<National_Outings_Trip_Staff__c> staffList = getRelatedObjList('National_Outings_Trip_Staff__c', tripId, retVal);
        for(National_Outings_Trip_Staff__c staff : staffList) {
            if(staff.Role__c != 'Leader') {
                relObjList.add(staff);
            }
        }

        List<Database.SaveResult> rsltList = Database.insert(relObjList);

        return retVal;
    }
    @AuraEnabled
    public static void markUploaded(List<String> idList) {
        List<National_Outings_Trip__c> tripsToUpdate = new List<National_Outings_Trip__c>();
        for(String tripId : idList) {
            tripsToUpdate.add(new National_Outings_Trip__c(Id = tripId, Status__c = 'Uploaded to TRAIL'));
        }
        update tripsToUpdate;
    }

    private static List<SObject> getRelatedObjList(String objName, Id fromTripId, Id toTripId) {
        List<SObject> toObjList = new List<SObject>();
        String query = 'SELECT ' +
            getFieldList(objName) +
            ' FROM ' + objName + ' WHERE National_Outings_Trip__c = :fromTripId';
        List<SObject> fromObjList = Database.query(query);
        for(SObject fromObj : fromObjList) {
            SObject toObj = fromObj.clone(false, true, false, false);
            toObj.put('National_Outings_Trip__c', toTripId);
            toObjList.add(toObj);
        }
        return toObjList;
    }

    private static String getFieldList(String objName) {
        Map <String, Schema.SObjectField> fieldMap = Schema.getGlobalDescribe().get(objName).getDescribe().fields.getMap();
        List<String> fieldNames = new List<String>();
        for( String fieldName : fieldMap.keySet() ) {
            Schema.SObjectField field = fieldMap.get(fieldName);
            if(field.getDescribe().isUpdateable()) {
                fieldNames.add( fieldName );
            }
        }
        return String.join(fieldNames, ','); 
    }
}