force-app/main/default/objects/National_Outings_Trip__c/National_Outings_Trip__c.object-meta.xml
<CustomObject>
    <label>National Outings Trip</label>
    <nameField>
        <label>National Outings Trip Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>National Outings Trips</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/National_Outings_Trip_Budget_Item__c/National_Outings_Trip_Budget_Item__c.object-meta.xml
<CustomObject>
    <label>National Outings Trip Budget Item</label>
    <nameField>
        <displayFormat>TI-{00000000}</displayFormat>
        <label>National Outings Trip Budget Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>National Outings Trip Budget Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/National_Outings_Trip_Budget_Item__c/fields/Budget_Category__c.field-meta.xml
<CustomField>
    <fullName>Budget_Category__c</fullName>
    <label>Budget Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Meals</fullName>
            </value>
            <value>
                <fullName>Volunteer Travel</fullName>
            </value>
            <value>
                <fullName>Concessionaires</fullName>
            </value>
            <value>
                <fullName>Transportation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/National_Outings_Trip_Budget_Item__c/fields/Factor_Type__c.field-meta.xml
<CustomField>
    <fullName>Factor_Type__c</fullName>
    <label>Factor Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Dollars</fullName>
            </value>
            <value>
                <fullName>Miles</fullName>
            </value>
            <value>
                <fullName>Days</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/National_Outings_Trip_Budget_Item__c/fields/Item_Category__c.field-meta.xml
<CustomField>
    <fullName>Item_Category__c</fullName>
    <label>Item Category</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/National_Outings_Trip_Budget_Item__c/fields/National_Outings_Trip__c.field-meta.xml
<CustomField>
    <fullName>National_Outings_Trip__c</fullName>
    <label>National Outings Trip</label>
    <referenceTo>National_Outings_Trip__c</referenceTo>
    <relationshipLabel>National Outings Trip Budget Items</relationshipLabel>
    <relationshipName>National_Outings_Trip_Budget_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/National_Outings_Trip_Budget_Item__c/fields/Number_Participants__c.field-meta.xml
<CustomField>
    <fullName>Number_Participants__c</fullName>
    <label>Number Participants</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/National_Outings_Trip_Budget_Item__c/fields/Number_Staff__c.field-meta.xml
<CustomField>
    <fullName>Number_Staff__c</fullName>
    <label>Number Staff</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/National_Outings_Trip_Budget_Item__c/fields/Option__c.field-meta.xml
<CustomField>
    <fullName>Option__c</fullName>
    <label>Option</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Trip</fullName>
            </value>
            <value>
                <fullName>Staff</fullName>
            </value>
            <value>
                <fullName>Participants</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/National_Outings_Trip_Budget_Item__c/fields/Participant_Amount__c.field-meta.xml
<CustomField>
    <fullName>Participant_Amount__c</fullName>
    <label>Participant Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/National_Outings_Trip_Budget_Item__c/fields/Staff_Amount__c.field-meta.xml
<CustomField>
    <fullName>Staff_Amount__c</fullName>
    <label>Staff Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/National_Outings_Trip_Budget_Item__c/fields/Staff_Role__c.field-meta.xml
<CustomField>
    <fullName>Staff_Role__c</fullName>
    <label>Staff Role</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/NatoutTripBudgetController.cls
public with sharing class NatoutTripBudgetController {
    @AuraEnabled(cacheable = true)
    public static List<National_Outings_Trip_Budget_Item__c> getVolTravelList(String tripId) {
        List<National_Outings_Trip_Budget_Item__c> budgetList = [
            SELECT Id, Item_Category__c, Amount__c, Factor_Type__c, Staff_Role__c  
            FROM National_Outings_Trip_Budget_Item__c
            WHERE National_Outings_Trip__c = :tripId
                AND Budget_Category__c = 'Volunteer Travel'
        ];
        return budgetList;
    }  
    @AuraEnabled(cacheable = true)
    public static List<National_Outings_Trip_Budget_Item__c> getMealsList(String tripId) {
        List<National_Outings_Trip_Budget_Item__c> budgetList = [
            SELECT Id, Item_Category__c, Day_Number__c, Participant_Amount__c, Staff_Amount__c, Number_Participants__c, Number_Staff__c
            FROM National_Outings_Trip_Budget_Item__c
            WHERE National_Outings_Trip__c = :tripId
                AND Budget_Category__c = 'Meals'
            ORDER BY Day_Number__c
        ];
        return budgetList;
    }  
    @AuraEnabled(cacheable = true)
    public static List<National_Outings_Trip_Budget_Item__c> getTransportationList(String tripId) {
        List<National_Outings_Trip_Budget_Item__c> budgetList = [
            SELECT Id, Item_Category__c, Option__c, Amount__c
            FROM National_Outings_Trip_Budget_Item__c
            WHERE National_Outings_Trip__c = :tripId
                AND Budget_Category__c = 'Transportation'
        ];
        return budgetList;
    }  
    @AuraEnabled(cacheable = true)
    public static List<National_Outings_Trip_Budget_Item__c> getConcessionaireList(String tripId) {
        List<National_Outings_Trip_Budget_Item__c> budgetList = [
            SELECT Id, Item_Category__c, Option__c, Amount__c, Number_Staff__c
            FROM National_Outings_Trip_Budget_Item__c
            WHERE National_Outings_Trip__c = :tripId
                AND Budget_Category__c = 'Concessionaires'
        ];
        return budgetList;
    }
}