force-app/main/default/objects/National_Outings_Trip__c/National_Outings_Trip__c.object-meta.xml
<CustomObject>
    <label>National Outings Trip</label>
    <nameField>
        <label>National Outings Trip Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>National Outings Trips</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/National_Outings_Trip__c/fields/Entry_Trail_Head__c.field-meta.xml
<CustomField>
    <fullName>Entry_Trail_Head__c</fullName>
    <label>Entry Trail Head</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/National_Outings_Trip__c/fields/Exit_Trail_Head__c.field-meta.xml
<CustomField>
    <fullName>Exit_Trail_Head__c</fullName>
    <label>Exit trailhead</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/National_Outings_Trip__c/fields/Participants__c.field-meta.xml
<CustomField>
    <fullName>Participants__c</fullName>
    <label>Number of Participants</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/National_Outings_Trip__c/fields/Permit_Comments__c.field-meta.xml
<CustomField>
    <fullName>Permit_Comments__c</fullName>
    <label>Permit Comments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/National_Outings_Trip__c/fields/Permit_Requirement_Options__c.field-meta.xml
<CustomField>
    <fullName>Permit_Requirement_Options__c</fullName>
    <defaultValue>&apos;Commercial Permit (s) are not required&apos;</defaultValue>
    <label>Permit Requirement Options</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Commercial Permit (s) are not required</fullName>
                <default>true</default>
                <label>Commercial Permit (s) are not required</label>
            </value>
            <value>
                <fullName>Permit Associate Staff will obtain Commercial Permit (s)</fullName>
            </value>
            <value>
                <fullName>Concessionaire will obtain all Commercial Permit (s)</fullName>
            </value>
            <value>
                <fullName>Concessionaire will obtain some Commercial Permit (s)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/National_Outings_Trip__c/fields/Planned_Staff__c.field-meta.xml
<CustomField>
    <fullName>Planned_Staff__c</fullName>
    <label>Planned Staff</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/National_Outings_Trip__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/National_Outings_Trip_Itinerary__c/National_Outings_Trip_Itinerary__c.object-meta.xml
<CustomObject>
    <label>National Outings Trip Itinerary</label>
    <nameField>
        <displayFormat>TI-{00000000}</displayFormat>
        <label>National Outings Trip Itinerary Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>National Outings Trip Itineraries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/National_Outings_Trip_Itinerary__c/fields/Camp_Lodge_Location__c.field-meta.xml
<CustomField>
    <fullName>Camp_Lodge_Location__c</fullName>
    <label>Camp/Lodge Location</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/National_Outings_Trip_Itinerary__c/fields/Day_Number__c.field-meta.xml
<CustomField>
    <fullName>Day_Number__c</fullName>
    <label>Day Number</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/National_Outings_Trip_Itinerary__c/fields/Land_Agency__c.field-meta.xml
<CustomField>
    <fullName>Land_Agency__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Land Agency</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>National Outings Trip Itineraries</relationshipLabel>
    <relationshipName>National_Outings_Trip_Itineraries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/National_Outings_Trip_Itinerary__c/fields/National_Outings_Trip__c.field-meta.xml
<CustomField>
    <fullName>National_Outings_Trip__c</fullName>
    <label>National Outings Trip</label>
    <referenceTo>National_Outings_Trip__c</referenceTo>
    <relationshipLabel>National Outings Trip Itineraries</relationshipLabel>
    <relationshipName>National_Outings_Trip_Itineraries</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/National_Outings_Trip_Itinerary__c/fields/Trails_Used__c.field-meta.xml
<CustomField>
    <fullName>Trails_Used__c</fullName>
    <label>Trails Used</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/National_Outings_Trip_Staff__c/National_Outings_Trip_Staff__c.object-meta.xml
<CustomObject>
    <label>National Outings Trip Staff</label>
    <nameField>
        <displayFormat>TS-{00000000}</displayFormat>
        <label>National Outing Trip Staff Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>National Outings Trip Staffs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/National_Outings_Trip_Staff__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>National Outings Trip Staffs</relationshipLabel>
    <relationshipName>National_Outings_Trip_Staffs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/National_Outings_Trip_Staff__c/fields/National_Outings_Trip__c.field-meta.xml
<CustomField>
    <fullName>National_Outings_Trip__c</fullName>
    <label>National Outings Trip</label>
    <referenceTo>National_Outings_Trip__c</referenceTo>
    <relationshipLabel>National Outings Trip Staffs</relationshipLabel>
    <relationshipName>National_Outings_Trip_Staffs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/National_Outings_Trip_Staff__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Assistant Commissary</fullName>
            </value>
            <value>
                <fullName>Assistant_Leader</fullName>
                <label>Assistant-Leader</label>
            </value>
            <value>
                <fullName>Assistant-Leader 2</fullName>
            </value>
            <value>
                <fullName>Assistant Leader 3</fullName>
            </value>
            <value>
                <fullName>Assistant Leader 4</fullName>
            </value>
            <value>
                <fullName>Assistant Trainee</fullName>
            </value>
            <value>
                <fullName>Associate Leader</fullName>
            </value>
            <value>
                <fullName>Board Liaison</fullName>
            </value>
            <value>
                <fullName>Co-Leader</fullName>
            </value>
            <value>
                <fullName>Commissary</fullName>
            </value>
            <value>
                <fullName>Conservation Coordinator</fullName>
            </value>
            <value>
                <fullName>Conservation Specialist</fullName>
            </value>
            <value>
                <fullName>Cook</fullName>
            </value>
            <value>
                <fullName>Crew</fullName>
            </value>
            <value>
                <fullName>Doctor</fullName>
            </value>
            <value>
                <fullName>Evaluation Coordinator</fullName>
            </value>
            <value>
                <fullName>Guide</fullName>
            </value>
            <value>
                <fullName>Home School Mentor</fullName>
            </value>
            <value>
                <fullName>Host</fullName>
            </value>
            <value>
                <fullName>Instructor</fullName>
            </value>
            <value>
                <fullName>Leader</fullName>
            </value>
            <value>
                <fullName>Leader Child</fullName>
            </value>
            <value>
                <fullName>Liaison</fullName>
            </value>
            <value>
                <fullName>Mentor Leader</fullName>
            </value>
            <value>
                <fullName>Mountaineering Specialist</fullName>
            </value>
            <value>
                <fullName>Naturalist</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Specialist</fullName>
            </value>
            <value>
                <fullName>Support Staff</fullName>
            </value>
            <value>
                <fullName>Trainee</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/NatoutTripItineraryController.cls
public with sharing class NatoutTripItineraryController {
    private static String tripId;
    private National_Outings_Trip__c trip;

    @AuraEnabled (cacheable=true)
    public static List<National_Outings_Trip_Itinerary__c> getItineraryList(String tripId) {
        List<National_Outings_Trip_Itinerary__c> itineraryList = [
            SELECT Id, Land_Agency__c, Land_Agency__r.Name,
            Day_Number__c, Camp_Lodge_Location__c, Trails_Used__c
            FROM National_Outings_Trip_Itinerary__c
            WHERE National_Outings_Trip__c = :tripId
            ORDER BY Day_Number__c
        ];
        return itineraryList;
    }
    public List<PrintReport> getReportList() {
        List<National_Outings_Trip_Itinerary__c> itList = getItineraryList(getTripId());
        List<PrintReport> reportList = new List<PrintReport>();
        Date startDate = getTrip().Start_Date__c;
        for(National_Outings_Trip_Itinerary__c it : itList) {
            reportList.add(
                new PrintReport(
                    it.Land_Agency__r.Name,
                    it.Day_Number__c,
                    startDate.addDays(Integer.valueOf(it.Day_Number__c) - 1),
                    it.Camp_Lodge_Location__c,
                    it.Trails_Used__c
                )
            );
        }
        return reportList;
    }
    private static String getTripId() {
        if(tripId == null) {
            tripId = ApexPages.currentPage().getParameters().get('id');
        }
        return tripId;
    }
    public National_Outings_Trip__c getTrip() {
        if(trip == null) {
            String tripId = getTripId();
            trip = [
                SELECT Name, Start_Date__c, End_Date__c,
                Participants__c, Planned_Staff__c, Title__c,
                Permit_Requirement_Options__c, Permit_Comments__c,
                Entry_Trail_Head__c, Exit_Trail_Head__c,
                (SELECT Contact__r.Name, Role__c FROM National_Outings_Trip_Staffs__r)
                FROM National_Outings_Trip__c WHERE Id = :tripId
            ];
        }
        return trip;
    }
    public class PrintReport {
        public String agency {get; set;}
        public Decimal dayNum {get; set;}
        public Date dayDate {get; set;}
        public String location {get; set;}
        public String trails {get; set;}
        public PrintReport(
            String agency,
            Decimal dayNum,
            Date dayDate,
            String location,
            String trails
        ) {
            this.agency = agency;
            this.dayNum = dayNum;
            this.dayDate = dayDate;
            this.location = location;
            this.trails = trails;
        }
    }
}