force-app/main/default/objects/National_Outings_Trip__c/National_Outings_Trip__c.object-meta.xml
<CustomObject>
    <label>National Outings Trip</label>
    <nameField>
        <label>National Outings Trip Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>National Outings Trips</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/National_Outings_Trip__c/fields/Activity_Type__c.field-meta.xml
<CustomField>
    <fullName>Activity_Type__c</fullName>
    <label>Activity Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Base Camp</fullName>
            </value>
            <value>
                <fullName>Bicycle</fullName>
            </value>
            <value>
                <fullName>Backpack</fullName>
            </value>
            <value>
                <fullName>Canoe</fullName>
            </value>
            <value>
                <fullName>Supported Trekking</fullName>
            </value>
            <value>
                <fullName>Hut-to-Hut Trekking</fullName>
            </value>
            <value>
                <fullName>Kayak</fullName>
            </value>
            <value>
                <fullName>Lodge</fullName>
            </value>
            <value>
                <fullName>Raft</fullName>
            </value>
            <value>
                <fullName>Small Boat</fullName>
            </value>
            <value>
                <fullName>Scuba</fullName>
            </value>
            <value>
                <fullName>Service/Volunteer</fullName>
            </value>
            <value>
                <fullName>Snow</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/National_Outings_Trip__c/fields/Area__c.field-meta.xml
<CustomField>
    <fullName>Area__c</fullName>
    <label>Area</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>National_Outings_Trip_Area</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/National_Outings_Trip__c/fields/Backpack_Rating__c.field-meta.xml
<CustomField>
    <fullName>Backpack_Rating__c</fullName>
    <label>Backpack Rating</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1 - Least Difficult</fullName>
            </value>
            <value>
                <fullName>2 - Less Difficult</fullName>
            </value>
            <value>
                <fullName>3 - Difficult</fullName>
            </value>
            <value>
                <fullName>4 - More Difficult</fullName>
            </value>
            <value>
                <fullName>5 - Most Difficult</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/National_Outings_Trip__c/fields/First_Time_Run__c.field-meta.xml
<CustomField>
    <fullName>First_Time_Run__c</fullName>
    <defaultValue>true</defaultValue>
    <label>First Time Run</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/National_Outings_Trip__c/fields/Fixed_Amount__c.field-meta.xml
<CustomField>
    <fullName>Fixed_Amount__c</fullName>
    <label>Fixed Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/National_Outings_Trip__c/fields/Geographic_Area__c.field-meta.xml
<CustomField>
    <fullName>Geographic_Area__c</fullName>
    <label>Geographic Area</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Africa</fullName>
            </value>
            <value>
                <fullName>Asia</fullName>
            </value>
            <value>
                <fullName>Central America</fullName>
            </value>
            <value>
                <fullName>Eastern Europe</fullName>
            </value>
            <value>
                <fullName>Northern Europe</fullName>
            </value>
            <value>
                <fullName>Pacific Basin</fullName>
            </value>
            <value>
                <fullName>South America</fullName>
            </value>
            <value>
                <fullName>Western Europe</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/National_Outings_Trip__c/fields/Group_Type__c.field-meta.xml
<CustomField>
    <fullName>Group_Type__c</fullName>
    <label>Group Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Beginners</fullName>
            </value>
            <value>
                <fullName>Family</fullName>
            </value>
            <value>
                <fullName>40s/50s</fullName>
            </value>
            <value>
                <fullName>Grandparent/Grandkids</fullName>
            </value>
            <value>
                <fullName>LGBT+</fullName>
            </value>
            <value>
                <fullName>Multigenerational</fullName>
            </value>
            <value>
                <fullName>Seniors (50+)</fullName>
            </value>
            <value>
                <fullName>Teen</fullName>
            </value>
            <value>
                <fullName>30s/40s</fullName>
            </value>
            <value>
                <fullName>Women</fullName>
            </value>
            <value>
                <fullName>20s/30s</fullName>
            </value>
            <value>
                <fullName>Training</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/National_Outings_Trip__c/fields/Latitude__c.field-meta.xml
<CustomField>
    <fullName>Latitude__c</fullName>
    <label>Latitude</label>
    <precision>14</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/National_Outings_Trip__c/fields/Longitude__c.field-meta.xml
<CustomField>
    <fullName>Longitude__c</fullName>
    <label>Longitude</label>
    <precision>15</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/National_Outings_Trip__c/fields/Meals_Budget_Option__c.field-meta.xml
<CustomField>
    <fullName>Meals_Budget_Option__c</fullName>
    <defaultValue>&apos;None&apos;</defaultValue>
    <label>Meals Budget Option</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>Subcommittee</fullName>
            </value>
            <value>
                <fullName>Day</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/National_Outings_Trip__c/fields/Meals_Comments__c.field-meta.xml
<CustomField>
    <fullName>Meals_Comments__c</fullName>
    <label>Meal Comments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/National_Outings_Trip__c/fields/Meals_First_Day__c.field-meta.xml
<CustomField>
    <fullName>Meals_First_Day__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Number of Meals on First Day</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/National_Outings_Trip__c/fields/Meals_Included__c.field-meta.xml
<CustomField>
    <fullName>Meals_Included__c</fullName>
    <label>Meals Included</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>All</fullName>
            </value>
            <value>
                <fullName>Most</fullName>
            </value>
            <value>
                <fullName>Some</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/National_Outings_Trip__c/fields/Meals_Last_Day__c.field-meta.xml
<CustomField>
    <fullName>Meals_Last_Day__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Meals Last Day</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/National_Outings_Trip__c/fields/Minimum_Age__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Age__c</fullName>
    <label>Minimum Age</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/National_Outings_Trip__c/fields/Participants__c.field-meta.xml
<CustomField>
    <fullName>Participants__c</fullName>
    <label>Number of Participants</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/National_Outings_Trip__c/fields/Permit_Comments__c.field-meta.xml
<CustomField>
    <fullName>Permit_Comments__c</fullName>
    <label>Permit Comments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/National_Outings_Trip__c/fields/Permit_Requirement_Options__c.field-meta.xml
<CustomField>
    <fullName>Permit_Requirement_Options__c</fullName>
    <defaultValue>&apos;Commercial Permit (s) are not required&apos;</defaultValue>
    <label>Permit Requirement Options</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Commercial Permit (s) are not required</fullName>
                <default>true</default>
                <label>Commercial Permit (s) are not required</label>
            </value>
            <value>
                <fullName>Permit Associate Staff will obtain Commercial Permit (s)</fullName>
            </value>
            <value>
                <fullName>Concessionaire will obtain all Commercial Permit (s)</fullName>
            </value>
            <value>
                <fullName>Concessionaire will obtain some Commercial Permit (s)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/National_Outings_Trip__c/fields/Planned_Staff__c.field-meta.xml
<CustomField>
    <fullName>Planned_Staff__c</fullName>
    <label>Planned Staff</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/National_Outings_Trip__c/fields/Prior_Trip_Copy_Changes__c.field-meta.xml
<CustomField>
    <fullName>Prior_Trip_Copy_Changes__c</fullName>
    <label>Prior Trip Copy Changes</label>
    <length>500</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/National_Outings_Trip__c/fields/Risks_Hazards__c.field-meta.xml
<CustomField>
    <fullName>Risks_Hazards__c</fullName>
    <label>Risks/Hazards</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/National_Outings_Trip__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/National_Outings_Trip__c/fields/States__c.field-meta.xml
<CustomField>
    <fullName>States__c</fullName>
    <label>States</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>State</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/National_Outings_Trip__c/fields/Subcommittee__c.field-meta.xml
<CustomField>
    <fullName>Subcommittee__c</fullName>
    <label>Subcommittee</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/National_Outings_Trip__c/fields/Trip_Copy__c.field-meta.xml
<CustomField>
    <fullName>Trip_Copy__c</fullName>
    <label>Trip Copy</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/National_Outings_Trip__c/fields/Trip_Type__c.field-meta.xml
<CustomField>
    <fullName>Trip_Type__c</fullName>
    <label>Trip Type</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/National_Outings_Trip_Agency__c/National_Outings_Trip_Agency__c.object-meta.xml
<CustomObject>
    <label>National Outings Trip Agency</label>
    <nameField>
        <displayFormat>TA-{00000000}</displayFormat>
        <label>National Outings Trip Agency Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>National Outings Trip Agencies</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/National_Outings_Trip_Agency__c/fields/National_Outings_Trip__c.field-meta.xml
<CustomField>
    <fullName>National_Outings_Trip__c</fullName>
    <label>National Outings Trip</label>
    <referenceTo>National_Outings_Trip__c</referenceTo>
    <relationshipLabel>National Outings Trip Agencies</relationshipLabel>
    <relationshipName>National_Outings_Trip_Agencies</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/National_Outings_Trip_Staff__c/National_Outings_Trip_Staff__c.object-meta.xml
<CustomObject>
    <label>National Outings Trip Staff</label>
    <nameField>
        <displayFormat>TS-{00000000}</displayFormat>
        <label>National Outing Trip Staff Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>National Outings Trip Staffs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/National_Outings_Trip_Staff__c/fields/National_Outings_Trip__c.field-meta.xml
<CustomField>
    <fullName>National_Outings_Trip__c</fullName>
    <label>National Outings Trip</label>
    <referenceTo>National_Outings_Trip__c</referenceTo>
    <relationshipLabel>National Outings Trip Staffs</relationshipLabel>
    <relationshipName>National_Outings_Trip_Staffs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/National_Outings_Trip_Vendor__c/National_Outings_Trip_Vendor__c.object-meta.xml
<CustomObject>
    <label>National Outings Trip Vendor</label>
    <nameField>
        <displayFormat>NOV-{00000000}</displayFormat>
        <label>National Outings Trip Vendor Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>National Outings Trip Vendors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/National_Outings_Trip_Vendor__c/fields/National_Outings_Trip__c.field-meta.xml
<CustomField>
    <fullName>National_Outings_Trip__c</fullName>
    <label>National Outings Trip</label>
    <referenceTo>National_Outings_Trip__c</referenceTo>
    <relationshipLabel>National Outings Trip Vendors</relationshipLabel>
    <relationshipName>National_Outings_Trip_Vendors</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/globalValueSets/National_Outings_Trip_Area.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Absaroka</fullName>
    </customValue>
    <customValue>
        <fullName>Acadia</fullName>
    </customValue>
    <customValue>
        <fullName>Adirondack</fullName>
    </customValue>
    <customValue>
        <fullName>Alpine Lakes</fullName>
    </customValue>
    <customValue>
        <fullName>Anaconda Pintler</fullName>
    </customValue>
    <customValue>
        <fullName>Ansel Adams</fullName>
    </customValue>
    <customValue>
        <fullName>Anza-Borrego</fullName>
    </customValue>
    <customValue>
        <fullName>Apache-Sitgreaves</fullName>
    </customValue>
    <customValue>
        <fullName>Aransas</fullName>
    </customValue>
    <customValue>
        <fullName>Arapahoe</fullName>
    </customValue>
    <customValue>
        <fullName>Arc Dome</fullName>
    </customValue>
    <customValue>
        <fullName>Arches</fullName>
    </customValue>
    <customValue>
        <fullName>Arctic Nntl Wildlife Ref</fullName>
    </customValue>
    <customValue>
        <fullName>Arkansas</fullName>
    </customValue>
    <customValue>
        <fullName>Ashley</fullName>
    </customValue>
    <customValue>
        <fullName>Assateague Island</fullName>
    </customValue>
    <customValue>
        <fullName>Aulavik</fullName>
    </customValue>
    <customValue>
        <fullName>Auyuittuq</fullName>
    </customValue>
    <customValue>
        <fullName>Aztec Ruins</fullName>
    </customValue>
    <customValue>
        <fullName>Badlands</fullName>
    </customValue>
    <customValue>
        <fullName>Bandelier</fullName>
    </customValue>
    <customValue>
        <fullName>Banff</fullName>
    </customValue>
    <customValue>
        <fullName>Baxter</fullName>
    </customValue>
    <customValue>
        <fullName>Beaverhead-Dearlodge</fullName>
    </customValue>
    <customValue>
        <fullName>Bentsen-Rio Grande Valley</fullName>
    </customValue>
    <customValue>
        <fullName>Big Basin</fullName>
    </customValue>
    <customValue>
        <fullName>Big Bend</fullName>
    </customValue>
    <customValue>
        <fullName>Big Horn</fullName>
    </customValue>
    <customValue>
        <fullName>Big Island (Hawaii)</fullName>
    </customValue>
    <customValue>
        <fullName>Big South Fork</fullName>
    </customValue>
    <masterLabel>National Outings Trip Area</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/NatoutTripExportControllerTest.cls
@isTest
public with sharing class NatoutTripExportControllerTest {
    static Id accountOrgTypeId;
    static Id accountHouseholdTypeId;
    static Id contactHouseholdTypeId;
    static {
        accountOrgTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Organization').getRecordTypeId();
        accountHouseholdTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Household').getRecordTypeId();
        contactHouseholdTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Household').getRecordTypeId();
    }
    static testMethod void myUnitTest() {
        National_Outings_Trip__c trip = new National_Outings_Trip__c(
            Name = 'Test Trip',
            Title__c = 'Test Trip',
            Trip_Type__c = 'Backpack - California',
            Subcommittee__c = 'Knapsack',
            Start_Date__c = Date.today(),
            End_Date__c = Date.today() + 4,
            Participants__c = 10,
            Planned_Staff__c = 2,
            Trip_Copy__c = 'Test trip',
            First_Time_Run__c = false,
            States__c = 'CA;NV;OR',
            Country__c = 'USA',
            Latitude__c = 90,
            Longitude__c = -120,
            Area__c = 'Big Sur;Big Basin;Big Horn',
            Geographic_Area__c = 'Asia',
            Activity_Type__c = 'Backpack;Bicycle;Base Camp',
            Group_Type__c = 'Multigenerational',
            Meals_Included__c = 'All',
            Backpack_Rating__c = '1 - Least Difficult',
            Minimum_Age__c = 16,
            Prior_Trip_Copy_Changes__c = 'Changes',
            Risks_Hazards__c = 'Risks and Hazards',
            Permit_Comments__c = 'Permit Comments',
            Permit_Requirement_Options__c = 'Permit Associate Staff will obtain Commercial Permit (s)',
            Meals_Budget_Option__c = 'Subcommittee',
            Meals_First_Day__c = 1,
            Meals_Last_Day__c = 2,
            Fixed_Amount__c = 10,
            Meals_Comments__c = 'Commment',
            Concessionaire_Comments__c = 'Commment',
            Supplies_Equipment__c = 10,
            Wilderness_Agency_Fees__c = 10,
            Commercial_Agency_Fees__c = 10,
            International_Countries__c = 'abc;def;ghi',
            Leader_Driving_Participants_During_Trip__c = true
        );
        insert trip;

        List<Account> accountList = new List<Account>();
		Account householdAccount = new Account(
            Name='Account1',
            RecordTypeId = accountHouseholdTypeId
        );
        accountList.add(householdAccount);
        Account vendorAccount1 = new Account(
            Name='Vendor Account 1',
            RecordTypeId = accountOrgTypeId
        );
        accountList.add(vendorAccount1);
        Account vendorAccount2 = new Account(
            Name='Vendor Account 2',
            RecordTypeId = accountOrgTypeId
        );
        accountList.add(vendorAccount2);
        Account vendorAccount3 = new Account(
            Name='Vendor Account 3',
            RecordTypeId = accountOrgTypeId
        );
        accountList.add(vendorAccount3);
        Account vendorAccount4 = new Account(
            Name='Vendor Account 4',
            RecordTypeId = accountOrgTypeId
        );
        accountList.add(vendorAccount4);
        Account vendorAccount5 = new Account(
            Name='Vendor Account 5',
            RecordTypeId = accountOrgTypeId
        );
        accountList.add(vendorAccount5);

        Account agency1 = new Account(
            Name='Agency 1',
            RecordTypeId = accountOrgTypeId
        );
        accountList.add(agency1);
        Account agency2 = new Account(
            Name='Agency 2',
            RecordTypeId = accountOrgTypeId
        );
        accountList.add(agency2);
        Account agency3 = new Account(
            Name='Agency 3',
            RecordTypeId = accountOrgTypeId
        );
        accountList.add(agency3);

        insert accountList;

        List<Contact> contactList = new List<Contact>();
        Contact contact1 = new Contact(
            AccountId = householdAccount.Id,
            FirstName = 'Test',
            LastName = 'Contact1',
            Email = 'test1.contact1@abc.com',
            RecordTypeId = contactHouseholdTypeId
        );
        contactList.add(contact1);
        Contact contact2 = new Contact(
            AccountId = householdAccount.Id,
            FirstName = 'Test',
            LastName = 'Contact2',
            Email = 'test2.contact2@abc.com',
            RecordTypeId = contactHouseholdTypeId
        );
        contactList.add(contact2);
        Contact contact3 = new Contact(
            AccountId = householdAccount.Id,
            FirstName = 'Test',
            LastName = 'Contact3',
            Email = 'test3.contact3@abc.com',
            RecordTypeId = contactHouseholdTypeId
        );
        contactList.add(contact3);
        Contact contact4 = new Contact(
            AccountId = householdAccount.Id,
            FirstName = 'Test',
            LastName = 'Contact4',
            Email = 'test4.contact4@abc.com',
            RecordTypeId = contactHouseholdTypeId
        );
        contactList.add(contact4);
        insert contactList;

        List<National_Outings_Trip_Staff__c> staffList = new List<National_Outings_Trip_Staff__c>();
        National_Outings_Trip_Staff__c staff1 = new National_Outings_Trip_Staff__c(
            National_Outings_Trip__c = trip.Id,
            Role__c = 'Leader',
            Contact__c = contact1.Id
        );
        staffList.add(staff1);
        National_Outings_Trip_Staff__c staff2 = new National_Outings_Trip_Staff__c(
            National_Outings_Trip__c = trip.Id,
            Role__c = 'Co-Leader',
            Contact__c = contact2.Id
        );
        staffList.add(staff2);
        National_Outings_Trip_Staff__c staff3 = new National_Outings_Trip_Staff__c(
            National_Outings_Trip__c = trip.Id,
            Role__c = 'Doctor',
            Contact__c = contact3.Id
        );
        staffList.add(staff3);
        National_Outings_Trip_Staff__c staff4 = new National_Outings_Trip_Staff__c(
            National_Outings_Trip__c = trip.Id,
            Role__c = 'Cook',
            Contact__c = contact4.Id
        );
        staffList.add(staff4);
        insert staffList;

        List<National_Outings_Trip_Vendor__c> vendorList = new List<National_Outings_Trip_Vendor__c>();
        National_Outings_Trip_Vendor__c vendor1 = new National_Outings_Trip_Vendor__c(
            National_Outings_Trip__c = trip.Id,
            Account__c = vendorAccount1.Id,
            Type__c = 'Lodging'
        );
        vendorList.add(vendor1);
        National_Outings_Trip_Vendor__c vendor2 = new National_Outings_Trip_Vendor__c(
            National_Outings_Trip__c = trip.Id,
            Account__c = vendorAccount2.Id,
            Type__c = 'Packer'
        );
        vendorList.add(vendor2);
        National_Outings_Trip_Vendor__c vendor3 = new National_Outings_Trip_Vendor__c(
            National_Outings_Trip__c = trip.Id,
            Account__c = vendorAccount3.Id,
            Type__c = 'Rentals'
        );
        vendorList.add(vendor3);
        National_Outings_Trip_Vendor__c vendor4 = new National_Outings_Trip_Vendor__c(
            National_Outings_Trip__c = trip.Id,
            Account__c = vendorAccount4.Id,
            Type__c = 'Shuttle'
        );
        vendorList.add(vendor4);
        National_Outings_Trip_Vendor__c vendor5 = new National_Outings_Trip_Vendor__c(
            National_Outings_Trip__c = trip.Id,
            Account__c = vendorAccount5.Id,
            Type__c = 'Lodging'
        );
        vendorList.add(vendor5);
        insert vendorList;

        List<National_Outings_Trip_Agency__c> agencyList = new List<National_Outings_Trip_Agency__c>();
        National_Outings_Trip_Agency__c tripAgency1 = new National_Outings_Trip_Agency__c(
            National_Outings_Trip__c = trip.Id,
            Account__c = agency1.Id
        );
        agencyList.add(tripAgency1);
        National_Outings_Trip_Agency__c tripAgency2 = new National_Outings_Trip_Agency__c(
            National_Outings_Trip__c = trip.Id,
            Account__c = agency2.Id
        );
        agencyList.add(tripAgency2);
        National_Outings_Trip_Agency__c tripAgency3 = new National_Outings_Trip_Agency__c(
            National_Outings_Trip__c = trip.Id,
            Account__c = agency3.Id
        );
        agencyList.add(tripAgency3);
        insert agencyList;

        Id trip2Id = NatoutTripCopy.copy(trip.Id);
        National_Outings_Trip__c trip2 = new National_Outings_Trip__c(
            Id=trip2Id,
            Subcommittee__c = 'International'
        );
        update trip2;

        NatoutTripExportController ctl = new NatoutTripExportController();
        PageReference pageRef = Page.NatoutTripExport;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('trips', trip.Id + ',' + trip2.Id);
        List<NatoutTripExportController.ExportRow> rowList = ctl.getExportList();
    }
}