force-app/main/default/objects/National_Outings_Trip__c/National_Outings_Trip__c.object-meta.xml
<CustomObject>
    <label>National Outings Trip</label>
    <nameField>
        <label>National Outings Trip Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>National Outings Trips</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/National_Outings_Trip__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/National_Outings_Trip__c/fields/Subcommittee__c.field-meta.xml
<CustomField>
    <fullName>Subcommittee__c</fullName>
    <label>Subcommittee</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/NatoutTripFilesServiceTest.cls
@isTest
public with sharing class NatoutTripFilesServiceTest {
    static testMethod void myUnitTest() {
        National_Outings_Trip__c trip = new National_Outings_Trip__c(
            Start_Date__c = Date.today(),
            End_Date__c = Date.today() + 2,
            Subcommittee__c = 'Knapsack'
        );
        insert trip;

        Id tripId = trip.Id;
        Id fileId = NatoutTripFilesService.saveTheChunkFile(trip.Id, 'TestFileName', 'TestContent', 'pdf', null, 'Itinerary');
        NatoutTripFilesService.saveTheChunkFile(tripId, 'TestFileName', 'TestContent', 'pdf', fileId, 'Itinerary');

        String rslts = NatoutTripFilesService.getContentDetails(tripId, 'Itinerary');
        NatoutTripFilesService.deleteContentDocument(tripId);
    }
}