force-app/main/default/objects/National_Outings_Trip__c/National_Outings_Trip__c.object-meta.xml
<CustomObject>
    <label>National Outings Trip</label>
    <nameField>
        <label>National Outings Trip Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>National Outings Trips</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/National_Outings_Trip__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/National_Outings_Trip__c/fields/Subcommittee__c.field-meta.xml
<CustomField>
    <fullName>Subcommittee__c</fullName>
    <label>Subcommittee</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/National_Outings_Trip_Collaborator__c/National_Outings_Trip_Collaborator__c.object-meta.xml
<CustomObject>
    <label>National Outings Trip Collaborator</label>
    <nameField>
        <displayFormat>NOCL-{00000000}</displayFormat>
        <label>National Outings Trip Collaborator Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>National Outings Trip Collaborators</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/National_Outings_Trip_Collaborator__c/fields/Access__c.field-meta.xml
<CustomField>
    <fullName>Access__c</fullName>
    <label>Access</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Edit</fullName>
            </value>
            <value>
                <fullName>Approve</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/National_Outings_Trip_Collaborator__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>National Outings Trip Collaborators</relationshipLabel>
    <relationshipName>National_Outings_Trip_Collaborators</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/National_Outings_Trip_Collaborator__c/fields/National_Outings_Trip__c.field-meta.xml
<CustomField>
    <fullName>National_Outings_Trip__c</fullName>
    <label>National Outings Trip</label>
    <referenceTo>National_Outings_Trip__c</referenceTo>
    <relationshipLabel>National Outings Trip Collaborators</relationshipLabel>
    <relationshipName>National_Outings_Trip_Collaborators</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/NatoutTripCollaboratorControllerTest.cls
@isTest
public with sharing class NatoutTripCollaboratorControllerTest {
    static Id accountHouseholdTypeId;
    static Id contactHouseholdTypeId;
    static Contact contact1;
    static Account account1;
    static {
        accountHouseholdTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Household').getRecordTypeId();
        contactHouseholdTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Household').getRecordTypeId();
    }
 static testMethod void myUnitTest() {
    Account account1 = new Account(
        Name='Account1',
        RecordTypeId = accountHouseholdTypeId
    );
    insert account1;
    contact1 = new Contact(
        AccountId = account1.Id,
        FirstName = 'Test',
        LastName = 'Contact1',
        Email = 'test1.contact1@abc.com',
        RecordTypeId = contactHouseholdTypeId
    );
    insert contact1;
    National_Outings_Trip__c trip = new National_Outings_Trip__c(
            Name = 'Test Trip',
            Subcommittee__c = 'Knapsack',
            Start_Date__c = Date.today(),
            End_Date__c = Date.today() + 2
        );
        insert trip;
     
        National_Outings_Trip_Collaborator__c collaborator = new National_Outings_Trip_Collaborator__c(
            National_Outings_Trip__c = trip.Id,
            Contact__c = contact1.Id,
            Access__c = 'Edit'
        );
        insert collaborator;
        List<National_Outings_Trip_Collaborator__c> collaboratorList = NatoutTripCollaboratorController.getCollaboratorList(trip.Id);
        System.assertEquals(1, collaboratorList.size());
    }
}