force-app/main/default/objects/National_Outings_Trip__c/National_Outings_Trip__c.object-meta.xml
<CustomObject>
    <label>National Outings Trip</label>
    <nameField>
        <label>National Outings Trip Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>National Outings Trips</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/National_Outings_Trip__c/fields/Sat_Phone_Ship_To_Address__c.field-meta.xml
<CustomField>
    <fullName>Sat_Phone_Ship_To_Address__c</fullName>
    <label>Sat Phone Ship-To Address</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/National_Outings_Trip__c/fields/Sat_Phone_Ship_To_City__c.field-meta.xml
<CustomField>
    <fullName>Sat_Phone_Ship_To_City__c</fullName>
    <label>Sat Phone Ship-To City</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/National_Outings_Trip__c/fields/Sat_Phone_Ship_To_Name__c.field-meta.xml
<CustomField>
    <fullName>Sat_Phone_Ship_To_Name__c</fullName>
    <label>Sat Phone Ship-To Name</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/National_Outings_Trip__c/fields/Sat_Phone_Ship_To_State__c.field-meta.xml
<CustomField>
    <fullName>Sat_Phone_Ship_To_State__c</fullName>
    <label>Sat Phone Ship-To State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>State</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/National_Outings_Trip__c/fields/Sat_Phone_Ship_To_Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Sat_Phone_Ship_To_Zip_Code__c</fullName>
    <label>Sat Phone Ship-To Zip Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/National_Outings_Trip__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&apos;Started&apos;</defaultValue>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Started</fullName>
                <default>true</default>
                <label>Started</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Returned</fullName>
            </value>
            <value>
                <fullName>Approved by Chair</fullName>
            </value>
            <value>
                <fullName>Approved by Staff</fullName>
            </value>
            <value>
                <fullName>Uploaded to TRAIL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/National_Outings_Trip_Staff__c/National_Outings_Trip_Staff__c.object-meta.xml
<CustomObject>
    <label>National Outings Trip Staff</label>
    <nameField>
        <displayFormat>TS-{00000000}</displayFormat>
        <label>National Outing Trip Staff Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>National Outings Trip Staffs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/National_Outings_Trip_Staff__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>National Outings Trip Staffs</relationshipLabel>
    <relationshipName>National_Outings_Trip_Staffs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/National_Outings_Trip_Staff__c/fields/National_Outings_Trip__c.field-meta.xml
<CustomField>
    <fullName>National_Outings_Trip__c</fullName>
    <label>National Outings Trip</label>
    <referenceTo>National_Outings_Trip__c</referenceTo>
    <relationshipLabel>National Outings Trip Staffs</relationshipLabel>
    <relationshipName>National_Outings_Trip_Staffs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/National_Outings_Trip_Staff__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Assistant Commissary</fullName>
            </value>
            <value>
                <fullName>Assistant_Leader</fullName>
                <label>Assistant-Leader</label>
            </value>
            <value>
                <fullName>Assistant-Leader 2</fullName>
            </value>
            <value>
                <fullName>Assistant Leader 3</fullName>
            </value>
            <value>
                <fullName>Assistant Leader 4</fullName>
            </value>
            <value>
                <fullName>Assistant Trainee</fullName>
            </value>
            <value>
                <fullName>Associate Leader</fullName>
            </value>
            <value>
                <fullName>Board Liaison</fullName>
            </value>
            <value>
                <fullName>Co-Leader</fullName>
            </value>
            <value>
                <fullName>Commissary</fullName>
            </value>
            <value>
                <fullName>Conservation Coordinator</fullName>
            </value>
            <value>
                <fullName>Conservation Specialist</fullName>
            </value>
            <value>
                <fullName>Cook</fullName>
            </value>
            <value>
                <fullName>Crew</fullName>
            </value>
            <value>
                <fullName>Doctor</fullName>
            </value>
            <value>
                <fullName>Evaluation Coordinator</fullName>
            </value>
            <value>
                <fullName>Guide</fullName>
            </value>
            <value>
                <fullName>Home School Mentor</fullName>
            </value>
            <value>
                <fullName>Host</fullName>
            </value>
            <value>
                <fullName>Instructor</fullName>
            </value>
            <value>
                <fullName>Leader</fullName>
            </value>
            <value>
                <fullName>Leader Child</fullName>
            </value>
            <value>
                <fullName>Liaison</fullName>
            </value>
            <value>
                <fullName>Mentor Leader</fullName>
            </value>
            <value>
                <fullName>Mountaineering Specialist</fullName>
            </value>
            <value>
                <fullName>Naturalist</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Specialist</fullName>
            </value>
            <value>
                <fullName>Support Staff</fullName>
            </value>
            <value>
                <fullName>Trainee</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/NatoutTripTriggerHandler.cls
public with sharing class NatoutTripTriggerHandler {
    public static void beforeInsert(List<National_Outings_Trip__c> tripList) {
        Id contactId = getUserContactId();
        if(contactId != null) {
            Contact userContact = [
                SELECT Name, MailingStreet, MailingCity, MailingState, MailingPostalCode
                FROM Contact
                WHERE Id = :contactId
            ];
            for(National_Outings_Trip__c trip : tripList) {
                trip.Sat_Phone_Ship_To_Name__c = userContact.Name;
                trip.Sat_Phone_Ship_To_Address__c = userContact.MailingStreet;
                trip.Sat_Phone_Ship_To_City__c = userContact.MailingCity;
                trip.Sat_Phone_Ship_To_State__c = userContact.MailingState;
                trip.Sat_Phone_Ship_To_Zip_Code__c = userContact.MailingPostalCode;
            }
        }
        return;
    }
    public static void afterInsert(List<National_Outings_Trip__c> tripList) {
        Id contactId = getUserContactId();
        if(contactId != null) {
            List<National_Outings_Trip_Staff__c> staffList = new List<National_Outings_Trip_Staff__c>();
            for(National_Outings_Trip__c trip : tripList) {
                staffList.add(
                    new National_Outings_Trip_Staff__c(
                        National_Outings_Trip__c = trip.Id,
                        Contact__c = contactId,
                        Role__c = 'Leader'
                    )
                );
            }
            insert staffList;
        }
    }
    public static void afterUpdate(List<National_Outings_Trip__c> tripList, Map<Id,National_Outings_Trip__c> oldMap ) {
        List<National_Outings_Trip__c> changedTrips = new List<National_Outings_Trip__c>();
        for(National_Outings_Trip__c trip : tripList) {
            National_Outings_Trip__c prevTrip = oldMap.get(trip.Id);
            if(prevTrip.Status__c != trip.Status__c) {
                changedTrips.add(trip);
            }
        }
        if( ! changedTrips.isEmpty() ) {
            List<TriggeredSendEmail__c> emailList =
                NatoutEmailHandler.statusChanged(changedTrips, oldMap);
            //insert emailList;
            System.debug('emailList: ' + emailList);
        }
    }
    private static Id getUserContactId() {
        Id userId = UserInfo.getUserId();
        Id contactId=null;
        if(UserInfo.getUserType() == 'Standard') {
            List<User_Lookups__c> uLookupList = [
                SELECT Contact__c FROM User_Lookups__c WHERE User__c = :userId
            ];
            if(uLookupList.size() > 0) {
                contactId = uLookupList[0].Contact__c;
            }
        }
        else {
            contactId = [select ContactId from User where Id=:userId].ContactId;
        }
        return contactId;
    }
}