force-app/main/default/objects/National_Outings_Trip__c/National_Outings_Trip__c.object-meta.xml
<CustomObject>
    <label>National Outings Trip</label>
    <nameField>
        <label>National Outings Trip Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>National Outings Trips</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/National_Outings_Trip__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/National_Outings_Trip__c/fields/Subcommittee__c.field-meta.xml
<CustomField>
    <fullName>Subcommittee__c</fullName>
    <label>Subcommittee</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/National_Outings_Trip_Comments__c/National_Outings_Trip_Comments__c.object-meta.xml
<CustomObject>
    <label>National Outings Trip Comments</label>
    <nameField>
        <displayFormat>NOTC-{00000000}</displayFormat>
        <label>National Outings Trip Comments Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>National Outings Trip Comments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/National_Outings_Trip_Comments__c/fields/Comments__c.field-meta.xml
<CustomField>
    <fullName>Comments__c</fullName>
    <label>Comments</label>
    <length>131000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/National_Outings_Trip_Comments__c/fields/National_Outings_Trip__c.field-meta.xml
<CustomField>
    <fullName>National_Outings_Trip__c</fullName>
    <label>National Outings Trip</label>
    <referenceTo>National_Outings_Trip__c</referenceTo>
    <relationshipLabel>National Outings Trip Comments</relationshipLabel>
    <relationshipName>National_Outings_Trip_Comments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/NatoutTripCommentsControllerTest.cls
@isTest
public with sharing class NatoutTripCommentsControllerTest {
    static testMethod void myUnitTest() {
        National_Outings_Trip__c trip = new National_Outings_Trip__c(
                Name = 'Test Trip',
                Subcommittee__c = 'Knapsack',
                Start_Date__c = Date.today(),
                End_Date__c = Date.today() + 2
            );
            insert trip;
         
            National_Outings_Trip_Comments__c comment = new National_Outings_Trip_Comments__c(
                National_Outings_Trip__c = trip.Id,
                Comments__c = 'This is a Test'
            );
            insert comment;
            List<National_Outings_Trip_Comments__c> commentsList = NatoutTripCommentsController.getCommentsList(trip.Id);
            System.assertEquals(1, commentsList.size());
        }
    }