force-app/main/default/objects/National_Outings_Trip__c/National_Outings_Trip__c.object-meta.xml
<CustomObject>
    <label>National Outings Trip</label>
    <nameField>
        <label>National Outings Trip Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>National Outings Trips</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/National_Outings_Trip__c/fields/Post_Trip_Report_Date_Submitted__c.field-meta.xml
<CustomField>
    <fullName>Post_Trip_Report_Date_Submitted__c</fullName>
    <label>Post Trip Report Date Submitted</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/National_Outings_Trip__c/fields/Post_Trip_Report_Due__c.field-meta.xml
<CustomField>
    <fullName>Post_Trip_Report_Due__c</fullName>
    <formula>End_Date__c &lt; TODAY()</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Post Trip Report Due</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/National_Outings_Trip__c/fields/Post_Trip_Report_Itinerary__c.field-meta.xml
<CustomField>
    <fullName>Post_Trip_Report_Itinerary__c</fullName>
    <label>Post Trip Report Itinerary</label>
    <length>131000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/National_Outings_Trip__c/fields/Post_Trip_Report_Medical__c.field-meta.xml
<CustomField>
    <fullName>Post_Trip_Report_Medical__c</fullName>
    <label>Post Trip Report Medical</label>
    <length>131000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/National_Outings_Trip__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/National_Outings_Trip__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&apos;Started&apos;</defaultValue>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Started</fullName>
                <default>true</default>
                <label>Started</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Returned</fullName>
            </value>
            <value>
                <fullName>Approved by Chair</fullName>
            </value>
            <value>
                <fullName>Approved by Staff</fullName>
            </value>
            <value>
                <fullName>Uploaded to TRAIL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/National_Outings_Trip__c/fields/Subcommittee__c.field-meta.xml
<CustomField>
    <fullName>Subcommittee__c</fullName>
    <label>Subcommittee</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/NatoutTripPostTripReportTest.cls
@isTest
public with sharing class NatoutTripPostTripReportTest {
    static testMethod void myUnitTest() {
        National_Outings_Trip__c trip = new National_Outings_Trip__c(
            Start_Date__c = Date.today().addDays(-10),
            End_Date__c = Date.today().addDays(-8),
            Subcommittee__c = 'Knapsack',
            Status__c = 'Uploaded to TRAIL'
        );
        insert trip;
        NatoutTripPostTripReport.submitReport(trip.Id, 'Test Itinerary', 'Test Medical');
        trip = [
            SELECT Id, 
                Post_Trip_Report_Itinerary__c,
                Post_Trip_Report_Medical__c,
                Post_Trip_Report_Due__c, 
                Post_Trip_Report_Date_Submitted__c
            FROM National_Outings_Trip__c 
            WHERE Id=:trip.Id
        ];
        System.assertEquals('Test Itinerary', trip.Post_Trip_Report_Itinerary__c);
        System.assertEquals('Test Medical', trip.Post_Trip_Report_Medical__c);
        System.assertEquals(true, trip.Post_Trip_Report_Due__c);
        System.assertNotEquals(null, trip.Post_Trip_Report_Date_Submitted__c);
        
        List<TriggeredSendEmail__c> emailList = [
            SELECT Id from TriggeredSendEmail__c
        ];
        System.assertEquals(1, emailList.size()); 

        NatoutTripPostTripReport.submitReport(trip.Id, '', '');
        emailList = [
            SELECT Id from TriggeredSendEmail__c
        ];
        System.assertEquals(2, emailList.size()); 

    }
}