force-app/main/default/objects/National_Outings_Trip__c/National_Outings_Trip__c.object-meta.xml
<CustomObject>
    <label>National Outings Trip</label>
    <nameField>
        <label>National Outings Trip Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>National Outings Trips</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/National_Outings_Trip_Collaborator__c/National_Outings_Trip_Collaborator__c.object-meta.xml
<CustomObject>
    <label>National Outings Trip Collaborator</label>
    <nameField>
        <displayFormat>NOCL-{00000000}</displayFormat>
        <label>National Outings Trip Collaborator Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>National Outings Trip Collaborators</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/National_Outings_Trip_Collaborator__c/fields/Access__c.field-meta.xml
<CustomField>
    <fullName>Access__c</fullName>
    <label>Access</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Edit</fullName>
            </value>
            <value>
                <fullName>Approve</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/National_Outings_Trip_Collaborator__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>National Outings Trip Collaborators</relationshipLabel>
    <relationshipName>National_Outings_Trip_Collaborators</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/National_Outings_Trip_Collaborator__c/fields/National_Outings_Trip__c.field-meta.xml
<CustomField>
    <fullName>National_Outings_Trip__c</fullName>
    <label>National Outings Trip</label>
    <referenceTo>National_Outings_Trip__c</referenceTo>
    <relationshipLabel>National Outings Trip Collaborators</relationshipLabel>
    <relationshipName>National_Outings_Trip_Collaborators</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/NatoutTripCollaboratorController.cls
public with sharing class NatoutTripCollaboratorController {
    @AuraEnabled (cacheable=true)
    public static List<National_Outings_Trip_Collaborator__c> getCollaboratorList(String tripId) {
        List<National_Outings_Trip_Collaborator__c> collaboratorList = [
            SELECT Id, Contact__r.Name, Access__c
            FROM National_Outings_Trip_Collaborator__c
            WHERE National_Outings_Trip__c = :tripId
        ];
        return collaboratorList;
    }
}