force-app/main/default/objects/National_Outings_Trip__c/National_Outings_Trip__c.object-meta.xml
<CustomObject>
    <label>National Outings Trip</label>
    <nameField>
        <label>National Outings Trip Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>National Outings Trips</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/National_Outings_Trip__c/fields/Commercial_Agency_Fees__c.field-meta.xml
<CustomField>
    <fullName>Commercial_Agency_Fees__c</fullName>
    <label>Commercial Agency Fees</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/National_Outings_Trip__c/fields/Communication_Devices__c.field-meta.xml
<CustomField>
    <fullName>Communication_Devices__c</fullName>
    <label>Communication Devices</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/National_Outings_Trip__c/fields/First_Time_Run__c.field-meta.xml
<CustomField>
    <fullName>First_Time_Run__c</fullName>
    <defaultValue>true</defaultValue>
    <label>First Time Run</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/National_Outings_Trip__c/fields/Fixed_Amount__c.field-meta.xml
<CustomField>
    <fullName>Fixed_Amount__c</fullName>
    <label>Fixed Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/National_Outings_Trip__c/fields/Meals_Budget_Option__c.field-meta.xml
<CustomField>
    <fullName>Meals_Budget_Option__c</fullName>
    <defaultValue>&apos;None&apos;</defaultValue>
    <label>Meals Budget Option</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>Subcommittee</fullName>
            </value>
            <value>
                <fullName>Day</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/National_Outings_Trip__c/fields/Meals_First_Day__c.field-meta.xml
<CustomField>
    <fullName>Meals_First_Day__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Number of Meals on First Day</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/National_Outings_Trip__c/fields/Meals_Last_Day__c.field-meta.xml
<CustomField>
    <fullName>Meals_Last_Day__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Meals Last Day</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/National_Outings_Trip__c/fields/Participants__c.field-meta.xml
<CustomField>
    <fullName>Participants__c</fullName>
    <label>Number of Participants</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/National_Outings_Trip__c/fields/Planned_Staff__c.field-meta.xml
<CustomField>
    <fullName>Planned_Staff__c</fullName>
    <label>Planned Staff</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/National_Outings_Trip__c/fields/Postage__c.field-meta.xml
<CustomField>
    <fullName>Postage__c</fullName>
    <label>Postage</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/National_Outings_Trip__c/fields/Shipping__c.field-meta.xml
<CustomField>
    <fullName>Shipping__c</fullName>
    <label>Shipping</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/National_Outings_Trip__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/National_Outings_Trip__c/fields/Subcommittee__c.field-meta.xml
<CustomField>
    <fullName>Subcommittee__c</fullName>
    <label>Subcommittee</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/National_Outings_Trip__c/fields/Supplies_Equipment__c.field-meta.xml
<CustomField>
    <fullName>Supplies_Equipment__c</fullName>
    <label>Supplies &amp; Equipment</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/National_Outings_Trip__c/fields/Trip_Type__c.field-meta.xml
<CustomField>
    <fullName>Trip_Type__c</fullName>
    <label>Trip Type</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/National_Outings_Trip__c/fields/Wilderness_Agency_Fees__c.field-meta.xml
<CustomField>
    <fullName>Wilderness_Agency_Fees__c</fullName>
    <label>Wilderness Agency Fees</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/National_Outings_Trip_Budget_Item__c/National_Outings_Trip_Budget_Item__c.object-meta.xml
<CustomObject>
    <label>National Outings Trip Budget Item</label>
    <nameField>
        <displayFormat>TI-{00000000}</displayFormat>
        <label>National Outings Trip Budget Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>National Outings Trip Budget Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/National_Outings_Trip_Budget_Item__c/fields/Budget_Category__c.field-meta.xml
<CustomField>
    <fullName>Budget_Category__c</fullName>
    <label>Budget Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Meals</fullName>
            </value>
            <value>
                <fullName>Volunteer Travel</fullName>
            </value>
            <value>
                <fullName>Concessionaires</fullName>
            </value>
            <value>
                <fullName>Transportation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/National_Outings_Trip_Budget_Item__c/fields/Factor_Type__c.field-meta.xml
<CustomField>
    <fullName>Factor_Type__c</fullName>
    <label>Factor Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Dollars</fullName>
            </value>
            <value>
                <fullName>Miles</fullName>
            </value>
            <value>
                <fullName>Days</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/National_Outings_Trip_Budget_Item__c/fields/Item_Category__c.field-meta.xml
<CustomField>
    <fullName>Item_Category__c</fullName>
    <label>Item Category</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/National_Outings_Trip_Budget_Item__c/fields/National_Outings_Trip__c.field-meta.xml
<CustomField>
    <fullName>National_Outings_Trip__c</fullName>
    <label>National Outings Trip</label>
    <referenceTo>National_Outings_Trip__c</referenceTo>
    <relationshipLabel>National Outings Trip Budget Items</relationshipLabel>
    <relationshipName>National_Outings_Trip_Budget_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/National_Outings_Trip_Budget_Item__c/fields/Number_Staff__c.field-meta.xml
<CustomField>
    <fullName>Number_Staff__c</fullName>
    <label>Number Staff</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/National_Outings_Trip_Budget_Item__c/fields/Option__c.field-meta.xml
<CustomField>
    <fullName>Option__c</fullName>
    <label>Option</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Trip</fullName>
            </value>
            <value>
                <fullName>Staff</fullName>
            </value>
            <value>
                <fullName>Participants</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/National_Outings_Trip_Budget_Item__c/fields/Participant_Amount__c.field-meta.xml
<CustomField>
    <fullName>Participant_Amount__c</fullName>
    <label>Participant Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/National_Outings_Trip_Budget_Item__c/fields/Staff_Amount__c.field-meta.xml
<CustomField>
    <fullName>Staff_Amount__c</fullName>
    <label>Staff Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/National_Outings_Trip_Budget_Item__c/fields/Staff_Role__c.field-meta.xml
<CustomField>
    <fullName>Staff_Role__c</fullName>
    <label>Staff Role</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/NatoutTripBudgetReportControllerTest.cls
@isTest
public with sharing class NatoutTripBudgetReportControllerTest {
    static testMethod void myUnitTest() {
        National_Outings_Trip__c trip = new National_Outings_Trip__c(
            Start_Date__c = Date.today(),
            End_Date__c = Date.today() + 2,
            Subcommittee__c = 'Knapsack',
            Wilderness_Agency_Fees__c = 100,
            Commercial_Agency_Fees__c = 100,
            Postage__c = 20,
            Communication_Devices__c = 20,
            Shipping__c = 20,
            Supplies_Equipment__c = 20,
            Meals_Budget_Option__c = 'Subcommittee',
            Fixed_Amount__c = 20,
            Participants__c = 12,
            Planned_Staff__c = 2,
            First_Time_Run__c = true,
            Trip_Type__c = 'Backpack - California',
            Meals_First_Day__c = 25,
            Meals_Last_Day__c = 25
        );
        insert trip;

        List<National_Outings_Trip_Budget_Item__c> itemList = new List<National_Outings_Trip_Budget_Item__c>();

        National_Outings_Trip_Budget_Item__c airfare = new National_Outings_Trip_Budget_Item__c(
            National_Outings_Trip__c = trip.Id,
            Budget_Category__c = 'Volunteer Travel',
            Amount__c = 100,
            Staff_Role__c = 'Leader',
            Item_Category__c = 'Airfare',
            Factor_Type__c = 'Dollars'
        );
        itemList.add(airfare);
        National_Outings_Trip_Budget_Item__c mileage = new National_Outings_Trip_Budget_Item__c(
            National_Outings_Trip__c = trip.Id,
            Budget_Category__c = 'Volunteer Travel',
            Amount__c = 100,
            Staff_Role__c = 'Co-Leader',
            Item_Category__c = 'Mileage',
            Factor_Type__c = 'Miles'
        );
        itemList.add(mileage);
        National_Outings_Trip_Budget_Item__c subsistence1 = new National_Outings_Trip_Budget_Item__c(
            National_Outings_Trip__c = trip.Id,
            Budget_Category__c = 'Volunteer Travel',
            Amount__c = 100,
            Staff_Role__c = 'Cook',
            Item_Category__c = 'Subsistence',
            Factor_Type__c = 'Days'
        );
        itemList.add(subsistence1);
        National_Outings_Trip_Budget_Item__c subsistence2 = new National_Outings_Trip_Budget_Item__c(
            National_Outings_Trip__c = trip.Id,
            Budget_Category__c = 'Volunteer Travel',
            Amount__c = 100,
            Staff_Role__c = 'Asst Leader',
            Item_Category__c = 'Subsistence',
            Factor_Type__c = 'Days'
        );
        itemList.add(subsistence2);
        National_Outings_Trip_Budget_Item__c bus = new National_Outings_Trip_Budget_Item__c(
            National_Outings_Trip__c = trip.Id,
            Budget_Category__c = 'Transportation',
            Amount__c = 100,
            Item_Category__c = 'Bus',
            Option__c = 'Trip'
        );
        itemList.add(bus);
        National_Outings_Trip_Budget_Item__c gratuities1 = new National_Outings_Trip_Budget_Item__c(
            National_Outings_Trip__c = trip.Id,
            Budget_Category__c = 'Transportation',
            Amount__c = 100,
            Item_Category__c = 'Gratuities',
            Option__c = 'Participants'
        );
        itemList.add(gratuities1);
        National_Outings_Trip_Budget_Item__c gratuities2 = new National_Outings_Trip_Budget_Item__c(
            National_Outings_Trip__c = trip.Id,
            Budget_Category__c = 'Transportation',
            Amount__c = 80,
            Item_Category__c = 'Gratuities',
            Option__c = 'Staff'
        );
        itemList.add(gratuities2);
        National_Outings_Trip_Budget_Item__c concess1 = new National_Outings_Trip_Budget_Item__c(
            National_Outings_Trip__c = trip.Id,
            Budget_Category__c = 'Concessionaires',
            Amount__c = 100,
            Item_Category__c = 'Campground',
            Option__c = 'Trip'
        );
        itemList.add(concess1);
        National_Outings_Trip_Budget_Item__c meals = new National_Outings_Trip_Budget_Item__c(
            National_Outings_Trip__c = trip.Id,
            Budget_Category__c = 'Meals',
            Staff_Amount__c = 20,
            Number_Staff__c = 2,
            Participant_Amount__c = 20
        );
        itemList.add(meals);

        insert itemList;

        NatoutTripBudgetReportController ctl = new NatoutTripBudgetReportController();
        PageReference pageRef = Page.NatoutTripBudgetReport;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('trip', trip.Id);

        NatoutTripBudgetReportController.VolTravel volTravel = ctl.getVolTravel();
        Decimal role1Total = volTravel.getRole1Total();
        Decimal role2Total = volTravel.getRole2Total();
        Decimal role3Total = volTravel.getRole3Total();
        Decimal role4Total = volTravel.getRole4Total();
        Decimal grandTotal1 = volTravel.getGrandTotal();
        for(NatoutTripBudgetReportController.VolTravelRow row : volTravel.itemList) {
            Decimal role1Amount = row.getRole1Amount();
            Decimal role2Amount = row.getRole2Amount();
            Decimal role3Amount = row.getRole3Amount();
            Decimal role4Amount = row.getRole4Amount();
            Decimal categoryTotal = row.getCategoryTotal();
        }
        NatoutTripBudgetReportController.BudgetCategory transport = ctl.getTransport();
        Decimal tripTotal = transport.getTripTotal();
        Decimal staffTotal = transport.getStaffTotal();
        Decimal partTotal = transport.getPartTotal();
        Decimal grandTotal2 = transport.getGrandTotal();
        NatoutTripBudgetReportController.BudgetCategory concess = ctl.getConcessionaires();
        NatoutTripBudgetReportController.SimpleList other = ctl.getOtherList();
        Decimal tripPrice = ctl.getTripPrice();
        for(NatoutTripBudgetReportController.BudgetRow row : transport.itemList) {
            Decimal tripAmount = row.getTripAmount();
            Decimal staffAmount = row.getStaffAmount();
            Decimal partAmount = row.getPartAmount();
            Decimal totalAmount = row.getTotalAmount();
        }

        trip.Meals_Budget_Option__c = 'Day';
        update trip;
        ctl = new NatoutTripBudgetReportController();
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('trip', trip.Id);
        NatoutTripBudgetReportController.SimpleList mealsList = ctl.getMeals();

        trip.Meals_Budget_Option__c = 'None';
        update trip;
        ctl = new NatoutTripBudgetReportController();
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('trip', trip.Id);
        mealsList = ctl.getMeals();

        trip.Participants__c = null;
        trip.Meals_Budget_Option__c = 'Day';
        update trip;
        ctl = new NatoutTripBudgetReportController();
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('trip', trip.Id);
        mealsList = ctl.getMeals();

        Decimal total = mealsList.getTotal();
        for(NatoutTripBudgetReportController.SimpleRow row : ctl.getOtherList().itemList) {
            Decimal amount = row.getAmount();
        }
        tripPrice = ctl.getTripPrice();

    }
}