force-app/main/default/objects/National_Outings_Trip__c/National_Outings_Trip__c.object-meta.xml
<CustomObject>
    <label>National Outings Trip</label>
    <nameField>
        <label>National Outings Trip Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>National Outings Trips</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/National_Outings_Trip_Agency__c/National_Outings_Trip_Agency__c.object-meta.xml
<CustomObject>
    <label>National Outings Trip Agency</label>
    <nameField>
        <displayFormat>TA-{00000000}</displayFormat>
        <label>National Outings Trip Agency Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>National Outings Trip Agencies</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/National_Outings_Trip_Agency__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>National Outings Trip Agencies</relationshipLabel>
    <relationshipName>National_Outings_Trip_Agencies</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/National_Outings_Trip_Agency__c/fields/National_Outings_Trip__c.field-meta.xml
<CustomField>
    <fullName>National_Outings_Trip__c</fullName>
    <label>National Outings Trip</label>
    <referenceTo>National_Outings_Trip__c</referenceTo>
    <relationshipLabel>National Outings Trip Agencies</relationshipLabel>
    <relationshipName>National_Outings_Trip_Agencies</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/NatoutTripAgenciesController.cls
public with sharing class NatoutTripAgenciesController {
    public NatoutTripAgenciesController() {

    }
    @AuraEnabled (cacheable=true)
    public static List<National_Outings_Trip_Agency__c> getAgencyList(String tripId) {
        System.debug('Retrieving staff for trip Id: ' + tripId);
        List<National_Outings_Trip_Agency__c> agencyList = [
            SELECT Id, Account__c, Account__r.Name
            FROM National_Outings_Trip_Agency__c
            WHERE National_Outings_Trip__c = :tripId
        ];
        System.debug('Returning agencyList: ' + agencyList);
        return agencyList;
    }
}