force-app/main/default/objects/National_Outings_Trip__c/National_Outings_Trip__c.object-meta.xml
<CustomObject>
    <label>National Outings Trip</label>
    <nameField>
        <label>National Outings Trip Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>National Outings Trips</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/National_Outings_Trip__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/National_Outings_Trip__c/fields/Subcommittee__c.field-meta.xml
<CustomField>
    <fullName>Subcommittee__c</fullName>
    <label>Subcommittee</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/National_Outings_Trip_Agency__c/National_Outings_Trip_Agency__c.object-meta.xml
<CustomObject>
    <label>National Outings Trip Agency</label>
    <nameField>
        <displayFormat>TA-{00000000}</displayFormat>
        <label>National Outings Trip Agency Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>National Outings Trip Agencies</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/National_Outings_Trip_Agency__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>National Outings Trip Agencies</relationshipLabel>
    <relationshipName>National_Outings_Trip_Agencies</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/National_Outings_Trip_Agency__c/fields/National_Outings_Trip__c.field-meta.xml
<CustomField>
    <fullName>National_Outings_Trip__c</fullName>
    <label>National Outings Trip</label>
    <referenceTo>National_Outings_Trip__c</referenceTo>
    <relationshipLabel>National Outings Trip Agencies</relationshipLabel>
    <relationshipName>National_Outings_Trip_Agencies</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/NatoutTripAgenciesControllerTest.cls
@isTest
public with sharing class NatoutTripAgenciesControllerTest {
    static Id accountOrgTypeId;
    static {
        accountOrgTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Organization').getRecordTypeId();
    }
    static testMethod void myUnitTest() {
		Account account = new Account(
            Name='Account1',
            RecordTypeId = accountOrgTypeId,
            Type = 'Ranger'
		);
        insert account;
        
        National_Outings_Trip__c trip = new National_Outings_Trip__c(
            Name = 'Test Trip',
            Subcommittee__c = 'Knapsack',
            Start_Date__c = Date.today(),
            End_Date__c = Date.today() + 2
        );
        insert trip;

        National_Outings_Trip_Agency__c agency = new National_Outings_Trip_Agency__c(
            National_Outings_Trip__c = trip.Id,
            Account__c = account.Id
        );
        insert agency;

        List<National_Outings_Trip_Agency__c> agencyList = NatoutTripAgenciesController.getAgencyList(trip.Id);

        System.assertEquals(1, agencyList.size());
    }
}