force-app/main/default/objects/National_Outings_Trip__c/National_Outings_Trip__c.object-meta.xml
<CustomObject>
    <label>National Outings Trip</label>
    <nameField>
        <label>National Outings Trip Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>National Outings Trips</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/National_Outings_Trip_Comments__c/National_Outings_Trip_Comments__c.object-meta.xml
<CustomObject>
    <label>National Outings Trip Comments</label>
    <nameField>
        <displayFormat>NOTC-{00000000}</displayFormat>
        <label>National Outings Trip Comments Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>National Outings Trip Comments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/National_Outings_Trip_Comments__c/fields/Comments__c.field-meta.xml
<CustomField>
    <fullName>Comments__c</fullName>
    <label>Comments</label>
    <length>131000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/National_Outings_Trip_Comments__c/fields/National_Outings_Trip__c.field-meta.xml
<CustomField>
    <fullName>National_Outings_Trip__c</fullName>
    <label>National Outings Trip</label>
    <referenceTo>National_Outings_Trip__c</referenceTo>
    <relationshipLabel>National Outings Trip Comments</relationshipLabel>
    <relationshipName>National_Outings_Trip_Comments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/National_Outings_Trip_Comments_Recip__c/National_Outings_Trip_Comments_Recip__c.object-meta.xml
<CustomObject>
    <label>National Outings Trip Comments Recip</label>
    <nameField>
        <displayFormat>TCR-{00000000}</displayFormat>
        <label>National Outings Trip Comments Recip Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>National Outings Trip Comments Recips</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/National_Outings_Trip_Comments_Recip__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>National Outings Trip Comments Recips</relationshipLabel>
    <relationshipName>National_Outings_Trip_Comments_Recips</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/National_Outings_Trip_Comments_Recip__c/fields/National_Outings_Trip_Comments__c.field-meta.xml
<CustomField>
    <fullName>National_Outings_Trip_Comments__c</fullName>
    <label>National Outings Trip Comments</label>
    <referenceTo>National_Outings_Trip_Comments__c</referenceTo>
    <relationshipLabel>National Outings Trip Comments Recips</relationshipLabel>
    <relationshipName>National_Outings_Trip_Comments_Recips</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/NatoutTripCommentsController.cls
public with sharing class NatoutTripCommentsController {
    @AuraEnabled (cacheable=true)
    public static List<National_Outings_Trip_Comments__c> getCommentsList(String tripId) {
        List<National_Outings_Trip_Comments__c> commentsList = [
            SELECT Id, CreatedBy.Name, CreatedDate, Comments__c,
            (SELECT Id, Contact__r.Name, Email__c, Staff_Position__c FROM National_Outings_Trip_Comments_Recips__r)
            FROM National_Outings_Trip_Comments__c
            WHERE National_Outings_Trip__c = :tripId
            ORDER BY CreatedDate
        ];
        return commentsList;
    }
}