force-app/main/default/objects/National_Outings_Trip__c/National_Outings_Trip__c.object-meta.xml
<CustomObject>
    <label>National Outings Trip</label>
    <nameField>
        <label>National Outings Trip Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>National Outings Trips</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/National_Outings_Trip_Staff__c/National_Outings_Trip_Staff__c.object-meta.xml
<CustomObject>
    <label>National Outings Trip Staff</label>
    <nameField>
        <displayFormat>TS-{00000000}</displayFormat>
        <label>National Outing Trip Staff Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>National Outings Trip Staffs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/National_Outings_Trip_Staff__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>National Outings Trip Staffs</relationshipLabel>
    <relationshipName>National_Outings_Trip_Staffs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/National_Outings_Trip_Staff__c/fields/National_Outings_Trip__c.field-meta.xml
<CustomField>
    <fullName>National_Outings_Trip__c</fullName>
    <label>National Outings Trip</label>
    <referenceTo>National_Outings_Trip__c</referenceTo>
    <relationshipLabel>National Outings Trip Staffs</relationshipLabel>
    <relationshipName>National_Outings_Trip_Staffs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/National_Outings_Trip_Staff__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Assistant Commissary</fullName>
            </value>
            <value>
                <fullName>Assistant_Leader</fullName>
                <label>Assistant-Leader</label>
            </value>
            <value>
                <fullName>Assistant-Leader 2</fullName>
            </value>
            <value>
                <fullName>Assistant Leader 3</fullName>
            </value>
            <value>
                <fullName>Assistant Leader 4</fullName>
            </value>
            <value>
                <fullName>Assistant Trainee</fullName>
            </value>
            <value>
                <fullName>Associate Leader</fullName>
            </value>
            <value>
                <fullName>Board Liaison</fullName>
            </value>
            <value>
                <fullName>Co-Leader</fullName>
            </value>
            <value>
                <fullName>Commissary</fullName>
            </value>
            <value>
                <fullName>Conservation Coordinator</fullName>
            </value>
            <value>
                <fullName>Conservation Specialist</fullName>
            </value>
            <value>
                <fullName>Cook</fullName>
            </value>
            <value>
                <fullName>Crew</fullName>
            </value>
            <value>
                <fullName>Doctor</fullName>
            </value>
            <value>
                <fullName>Evaluation Coordinator</fullName>
            </value>
            <value>
                <fullName>Guide</fullName>
            </value>
            <value>
                <fullName>Home School Mentor</fullName>
            </value>
            <value>
                <fullName>Host</fullName>
            </value>
            <value>
                <fullName>Instructor</fullName>
            </value>
            <value>
                <fullName>Leader</fullName>
            </value>
            <value>
                <fullName>Leader Child</fullName>
            </value>
            <value>
                <fullName>Liaison</fullName>
            </value>
            <value>
                <fullName>Mentor Leader</fullName>
            </value>
            <value>
                <fullName>Mountaineering Specialist</fullName>
            </value>
            <value>
                <fullName>Naturalist</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Specialist</fullName>
            </value>
            <value>
                <fullName>Support Staff</fullName>
            </value>
            <value>
                <fullName>Trainee</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/NatoutTripStaffController.cls
public with sharing class NatoutTripStaffController {
    @AuraEnabled (cacheable=true)
    public static List<National_Outings_Trip_Staff__c> getStaffList(String tripId) {
        System.debug('Retrieving staff for trip Id: ' + tripId);
        List<National_Outings_Trip_Staff__c> staffList = [
            SELECT Id, Contact__c, Contact__r.FirstName, Contact__r.LastName,
            National_Outings_Trip__c, 
            National_Outings_Trip__r.Name,
            Role__c 
            FROM National_Outings_Trip_Staff__c
            WHERE National_Outings_Trip__c = :tripId
        ];
        return staffList;
    }
}