force-app/main/default/objects/National_Outings_Trip__c/National_Outings_Trip__c.object-meta.xml
<CustomObject>
    <label>National Outings Trip</label>
    <nameField>
        <label>National Outings Trip Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>National Outings Trips</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/National_Outings_Trip_Vendor__c/National_Outings_Trip_Vendor__c.object-meta.xml
<CustomObject>
    <label>National Outings Trip Vendor</label>
    <nameField>
        <displayFormat>NOV-{00000000}</displayFormat>
        <label>National Outings Trip Vendor Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>National Outings Trip Vendors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/National_Outings_Trip_Vendor__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>National Outings Trip Vendors</relationshipLabel>
    <relationshipName>National_Outings_Trip_Vendors</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/National_Outings_Trip_Vendor__c/fields/National_Outings_Trip__c.field-meta.xml
<CustomField>
    <fullName>National_Outings_Trip__c</fullName>
    <label>National Outings Trip</label>
    <referenceTo>National_Outings_Trip__c</referenceTo>
    <relationshipLabel>National Outings Trip Vendors</relationshipLabel>
    <relationshipName>National_Outings_Trip_Vendors</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/NatoutTripVendorsController.cls
public with sharing class NatoutTripVendorsController {
    public NatoutTripVendorsController() {
    }
    @AuraEnabled (cacheable=true)
    public static List<National_Outings_Trip_Vendor__c> getVendorList(String tripId) {
        List<National_Outings_Trip_Vendor__c> vendorList = [
            SELECT Id, Type__c, Account__c, Account__r.Name
            FROM National_Outings_Trip_Vendor__c
            WHERE National_Outings_Trip__c = :tripId
            ORDER BY Type__c
        ];
        return vendorList;
    }
}