force-app/main/default/objects/National_Outings_Trip__c/National_Outings_Trip__c.object-meta.xml
<CustomObject>
    <label>National Outings Trip</label>
    <nameField>
        <label>National Outings Trip Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>National Outings Trips</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/National_Outings_Trip__c/fields/Commercial_Agency_Fees__c.field-meta.xml
<CustomField>
    <fullName>Commercial_Agency_Fees__c</fullName>
    <label>Commercial Agency Fees</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/National_Outings_Trip__c/fields/Communication_Devices__c.field-meta.xml
<CustomField>
    <fullName>Communication_Devices__c</fullName>
    <label>Communication Devices</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/National_Outings_Trip__c/fields/Fixed_Amount__c.field-meta.xml
<CustomField>
    <fullName>Fixed_Amount__c</fullName>
    <label>Fixed Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/National_Outings_Trip__c/fields/Meals_Budget_Option__c.field-meta.xml
<CustomField>
    <fullName>Meals_Budget_Option__c</fullName>
    <defaultValue>&apos;None&apos;</defaultValue>
    <label>Meals Budget Option</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>Subcommittee</fullName>
            </value>
            <value>
                <fullName>Day</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/National_Outings_Trip__c/fields/Meals_First_Day__c.field-meta.xml
<CustomField>
    <fullName>Meals_First_Day__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Number of Meals on First Day</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/National_Outings_Trip__c/fields/Meals_Last_Day__c.field-meta.xml
<CustomField>
    <fullName>Meals_Last_Day__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Meals Last Day</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/National_Outings_Trip__c/fields/Participants__c.field-meta.xml
<CustomField>
    <fullName>Participants__c</fullName>
    <label>Number of Participants</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/National_Outings_Trip__c/fields/Planned_Staff__c.field-meta.xml
<CustomField>
    <fullName>Planned_Staff__c</fullName>
    <label>Planned Staff</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/National_Outings_Trip__c/fields/Postage__c.field-meta.xml
<CustomField>
    <fullName>Postage__c</fullName>
    <label>Postage</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/National_Outings_Trip__c/fields/Shipping__c.field-meta.xml
<CustomField>
    <fullName>Shipping__c</fullName>
    <label>Shipping</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/National_Outings_Trip__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/National_Outings_Trip__c/fields/Subcommittee__c.field-meta.xml
<CustomField>
    <fullName>Subcommittee__c</fullName>
    <label>Subcommittee</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/National_Outings_Trip__c/fields/Supplies_Equipment__c.field-meta.xml
<CustomField>
    <fullName>Supplies_Equipment__c</fullName>
    <label>Supplies &amp; Equipment</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/National_Outings_Trip__c/fields/Trip_Type__c.field-meta.xml
<CustomField>
    <fullName>Trip_Type__c</fullName>
    <label>Trip Type</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/National_Outings_Trip__c/fields/Wilderness_Agency_Fees__c.field-meta.xml
<CustomField>
    <fullName>Wilderness_Agency_Fees__c</fullName>
    <label>Wilderness Agency Fees</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/National_Outings_Trip_Budget_Item__c/National_Outings_Trip_Budget_Item__c.object-meta.xml
<CustomObject>
    <label>National Outings Trip Budget Item</label>
    <nameField>
        <displayFormat>TI-{00000000}</displayFormat>
        <label>National Outings Trip Budget Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>National Outings Trip Budget Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/National_Outings_Trip_Budget_Item__c/fields/Budget_Category__c.field-meta.xml
<CustomField>
    <fullName>Budget_Category__c</fullName>
    <label>Budget Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Meals</fullName>
            </value>
            <value>
                <fullName>Volunteer Travel</fullName>
            </value>
            <value>
                <fullName>Concessionaires</fullName>
            </value>
            <value>
                <fullName>Transportation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/National_Outings_Trip_Budget_Item__c/fields/Item_Category__c.field-meta.xml
<CustomField>
    <fullName>Item_Category__c</fullName>
    <label>Item Category</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/National_Outings_Trip_Budget_Item__c/fields/National_Outings_Trip__c.field-meta.xml
<CustomField>
    <fullName>National_Outings_Trip__c</fullName>
    <label>National Outings Trip</label>
    <referenceTo>National_Outings_Trip__c</referenceTo>
    <relationshipLabel>National Outings Trip Budget Items</relationshipLabel>
    <relationshipName>National_Outings_Trip_Budget_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/National_Outings_Trip_Budget_Item__c/fields/Number_Staff__c.field-meta.xml
<CustomField>
    <fullName>Number_Staff__c</fullName>
    <label>Number Staff</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/National_Outings_Trip_Budget_Item__c/fields/Participant_Amount__c.field-meta.xml
<CustomField>
    <fullName>Participant_Amount__c</fullName>
    <label>Participant Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/National_Outings_Trip_Budget_Item__c/fields/Staff_Amount__c.field-meta.xml
<CustomField>
    <fullName>Staff_Amount__c</fullName>
    <label>Staff Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/NatoutTripBudgetExportControllerTest.cls
@isTest
public with sharing class NatoutTripBudgetExportControllerTest {
    static testMethod void myUnitTest() {
        National_Outings_Trip__c trip = new National_Outings_Trip__c(
            Name = 'Test Trip',
            Trip_Type__c = 'Backpack',
            Subcommittee__c = 'Knapsack',
            Start_Date__c = Date.today(),
            End_Date__c = Date.today() + 4,
            Participants__c = 10,
            Planned_Staff__c = 2,
            Fixed_Amount__c = 10,
            Commercial_Agency_Fees__c = 10,
            Meals_Budget_Option__c = 'Day',
            Meals_First_Day__c = 1,
            Meals_Last_Day__c =2,
            Shipping__c = 10,
            Postage__c = 10,
            Communication_Devices__c = 10,
            Supplies_Equipment__c = 10,
            Wilderness_Agency_Fees__c = 10
        );
        insert trip;

        List<National_Outings_Trip_Budget_Item__c> itemList = new List<National_Outings_Trip_Budget_Item__c>();
        itemList.add(new National_Outings_Trip_Budget_Item__c(
            National_Outings_Trip__c = trip.Id,
            Budget_Category__c = 'Volunteer Travel',
            Item_Category__c = 'Other - airport parking, baggage fees, etc.',
            Amount__c = 10
        ));

        itemList.add(new National_Outings_Trip_Budget_Item__c(
            National_Outings_Trip__c = trip.Id,
            Budget_Category__c = 'Meals',
            Number_Staff__c = 2,
            Staff_Amount__c = 20,
            Participant_Amount__c = 10
        ));

        itemList.add(new National_Outings_Trip_Budget_Item__c(
            National_Outings_Trip__c = trip.Id,
            Budget_Category__c = 'Transportation',
            Amount__c = 10
        ));

        itemList.add(new National_Outings_Trip_Budget_Item__c(
            National_Outings_Trip__c = trip.Id,
            Budget_Category__c = 'Concessionaires',
            Item_Category__c = 'Other',
            Amount__c = 10
        ));
        insert itemList;

        Id trip2Id = NatoutTripCopy.copy(trip.Id);

        NatoutTripBudgetExportController ctl = new NatoutTripBudgetExportController();
        PageReference pageRef = Page.NatoutTripBudgetExport;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('trips', trip.Id + ',' + trip2Id);
        List<NatoutTripBudgetExportController.ExportRow> rowList = ctl.getExportList();

    }
}