force-app/main/default/objects/National_Outings_Trip__c/National_Outings_Trip__c.object-meta.xml
<CustomObject>
    <label>National Outings Trip</label>
    <nameField>
        <label>National Outings Trip Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>National Outings Trips</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/National_Outings_Trip__c/fields/International_Countries__c.field-meta.xml
<CustomField>
    <fullName>International_Countries__c</fullName>
    <label>International Countries</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/National_Outings_Trip__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/National_Outings_Trip__c/fields/States_Provinces__c.field-meta.xml
<CustomField>
    <fullName>States_Provinces__c</fullName>
    <label>States/Provinces</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/National_Outings_Trip__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&apos;Started&apos;</defaultValue>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Started</fullName>
                <default>true</default>
                <label>Started</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Returned</fullName>
            </value>
            <value>
                <fullName>Approved by Chair</fullName>
            </value>
            <value>
                <fullName>Approved by Staff</fullName>
            </value>
            <value>
                <fullName>Uploaded to TRAIL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/National_Outings_Trip__c/fields/Subcommittee__c.field-meta.xml
<CustomField>
    <fullName>Subcommittee__c</fullName>
    <label>Subcommittee</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/National_Outings_Trip__c/fields/Trip_Type__c.field-meta.xml
<CustomField>
    <fullName>Trip_Type__c</fullName>
    <label>Trip Type</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/NatoutTripListControllerTest.cls
@isTest
public with sharing class NatoutTripListControllerTest {
    static testMethod void myUnitTest() {
        National_Outings_Trip__c trip = new National_Outings_Trip__c(
            Name = 'Test Trip',
            Subcommittee__c = 'Knapsack',
            Start_Date__c = Date.today(),
            End_Date__c = Date.today() + 2,
            Status__c = 'Started',
            Trip_Type__c = 'Backpack',
            States_Provinces__c = 'CA',
            Rack_Trip__c = true,
            International_Countries__c = 'China'
        );
        insert trip;
        NatoutTripListSearchCriteria criteria = new NatoutTripListSearchCriteria();
        criteria.dtBegin = dateToString(Date.today());
        criteria.dtEnd = dateToString(Date.today());
        criteria.userTrips = true;
        List<National_Outings_Trip__c> tripList = NatoutTripListController.getTripList(criteria);
        System.assertEquals(1, tripList.size());

        criteria.userTrips = false;
        criteria.subcomm = trip.Subcommittee__c;
        criteria.status = trip.Status__c;
        criteria.type = trip.Trip_Type__c;
        criteria.state = trip.States_Provinces__c;
        criteria.nameMatch = trip.Name;
        criteria.rackTrips = true;
        criteria.country = 'China';

        tripList = NatoutTripListController.getTripList(criteria);
        System.assertEquals(1, tripList.size());
    }
    private static String dateToString(Date inputDate) {
        Date d = inputDate;
        Datetime dt = Datetime.newInstance(d.year(), d.month(),d.day());
        return dt.format('yyyy-MM-dd');
    }
}