force-app/main/default/objects/National_Outings_Admin__c/National_Outings_Admin__c.object-meta.xml
<CustomObject>
    <label>National Outings Admin</label>
    <nameField>
        <displayFormat>NOA-{000000}</displayFormat>
        <label>National Outings Admin Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>National Outings Admins</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/National_Outings_Admin__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>National_Outings_Admins</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/National_Outings_Trip__c/National_Outings_Trip__c.object-meta.xml
<CustomObject>
    <label>National Outings Trip</label>
    <nameField>
        <label>National Outings Trip Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>National Outings Trips</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/National_Outings_Trip__c/fields/Budget_Approved_Date__c.field-meta.xml
<CustomField>
    <fullName>Budget_Approved_Date__c</fullName>
    <label>Budget Approved Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/National_Outings_Trip__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&apos;Started&apos;</defaultValue>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Started</fullName>
                <default>true</default>
                <label>Started</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Returned</fullName>
            </value>
            <value>
                <fullName>Approved by Chair</fullName>
            </value>
            <value>
                <fullName>Approved by Staff</fullName>
            </value>
            <value>
                <fullName>Uploaded to TRAIL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/National_Outings_Trip__c/fields/Subcommittee__c.field-meta.xml
<CustomField>
    <fullName>Subcommittee__c</fullName>
    <label>Subcommittee</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/National_Outings_Trip_Collaborator__c/National_Outings_Trip_Collaborator__c.object-meta.xml
<CustomObject>
    <label>National Outings Trip Collaborator</label>
    <nameField>
        <displayFormat>NOCL-{00000000}</displayFormat>
        <label>National Outings Trip Collaborator Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>National Outings Trip Collaborators</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/National_Outings_Trip_Collaborator__c/fields/Access__c.field-meta.xml
<CustomField>
    <fullName>Access__c</fullName>
    <label>Access</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Edit</fullName>
            </value>
            <value>
                <fullName>Approve</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/National_Outings_Trip_Collaborator__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>National Outings Trip Collaborators</relationshipLabel>
    <relationshipName>National_Outings_Trip_Collaborators</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/National_Outings_Trip_Collaborator__c/fields/National_Outings_Trip__c.field-meta.xml
<CustomField>
    <fullName>National_Outings_Trip__c</fullName>
    <label>National Outings Trip</label>
    <referenceTo>National_Outings_Trip__c</referenceTo>
    <relationshipLabel>National Outings Trip Collaborators</relationshipLabel>
    <relationshipName>National_Outings_Trip_Collaborators</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/NatoutUserInfo.cls
public without sharing class NatoutUserInfo {
    public static Id getContactId() {
        Id userId = System.UserInfo.getUserId();
        Id contactId;
        if(System.UserInfo.getUserType() == 'Standard') {
            contactId = [select Contact__c from User_Lookups__c where User__c = :userId].Contact__c;
        }
        else {
            contactId = [select ContactId from User where Id=:userId].ContactId;
        }
        return contactId;
    }
    @AuraEnabled (cacheable=true)
    public static UserAccess getUserAccess(String tripId) {
        Id userId = System.UserInfo.getUserId();
        Id contactId = getContactId();
        UserAccess uAccess = new UserAccess();

        /* National Outings Admins get full access */
        AggregateResult[] rslt = [
            SELECT COUNT(Id) cnt FROM National_Outings_Admin__c
            WHERE User__c = :userId
        ];
        Integer count = (Integer)rslt[0].get('cnt');
        if(count > 0) {
            uAccess.canEdit = true;
            uAccess.canApprove = true;
            uAccess.isAdmin = true;
            uAccess.canApproveBudget = canApproveBudget(contactId);
            return uAccess;
        }

        if(String.isEmpty(tripId)) {
            return uAccess;
        }

        National_Outings_Trip__c trip = [
            SELECT Id, OwnerId, Status__c, Subcommittee__c, Budget_Approved_Date__c
            FROM National_Outings_Trip__c
            WHERE Id = :tripId
        ];

        /* Trip creators get edit access until status is set to submitted */
        if(trip.OwnerId == userId) {
            if(trip.Status__c == 'Started' || trip.Status__c == 'Returned' || trip.Status__c == null) {
                uAccess.canEdit = true;
            }
        }

        /* Certain subcomittee positions get approval access */
        String subcommName = trip.Subcommittee__c;
        List<Leadership__c> ldrList = [
            SELECT Id FROM Leadership__c WHERE
            Contact__c = :contactId
            AND Club_Entity__r.Entity_Category__c = 'Outings' AND Club_Entity__r.Type__c = 'National Outing Subcomm' 
            AND Position_Status__c = 'Active' AND Leader_Position__r.Name IN ('Chair','Sub-comm Co-Chair','Vice Chair')
            AND Club_Entity__r.Name = :subcommName
        ];
        if( ! ldrList.isEmpty()) {
            switch on trip.Status__c {
                when 'Started', 'Returned', 'Submitted' {
                    uAccess.canApprove = true;
                    uAccess.canEdit = true;
                }
            }
        }

        /* Collaborators get appropriate access */
        if( ! (uAccess.canEdit && uAccess.canApprove) ) {
            List<National_Outings_Trip_Collaborator__c> collabList = [
                SELECT Access__c 
                FROM National_Outings_Trip_Collaborator__c
                WHERE Contact__c = :contactId AND National_Outings_Trip__c = :trip.Id
            ];
            for(National_Outings_Trip_Collaborator__c collab : collabList) {
                if(collab.Access__c == 'Approve') {
                    switch on trip.Status__c {
                        when 'Started', 'Returned', 'Submitted' {
                            uAccess.canApprove = true;
                            uAccess.canEdit = true;
                        }
                    }
                }
                else {
                    switch on trip.Status__c {
                        when 'Started', 'Returned' {
                            uAccess.canEdit = true;
                        }
                    }
                }
            }
        }
        if(trip.Status__c == 'Started' || trip.Status__c == 'Returned') {
            if(trip.Budget_Approved_Date__c == null) {
                uAccess.canApproveBudget = canApproveBudget(contactId);
                if(uAccess.canApproveBudget) {
                    uAccess.canEdit = true;
                }
            }
        }

        return uAccess;
    }
    public static Boolean canApproveBudget(String contactId) {
        List<Leadership__c> approverList = [
            SELECT
                Contact__c, 
                Contact__r.Email
            FROM Leadership__c 
            WHERE
                Contact__c = :contactId
                AND Club_Entity__r.Entity_Category__c = 'Outings' AND Club_Entity__r.Type__c = 'National Outing Subcomm' 
                AND Club_Entity__r.Name = 'International'
                AND Position_Status__c = 'Active' AND Leader_Position__r.Name = 'Trip Submission Approver'
        ];
        return ! approverList.isEmpty();
    }
    public class UserAccess {
        public UserAccess() {
            this.canEdit = false;
            this.canApprove = false;
            this.isAdmin = false;
            this.canApproveBudget = false;
        }
        @AuraEnabled
        public Boolean canEdit {get; set;}
        @AuraEnabled
        public Boolean canApprove {get; set;}
        @AuraEnabled
        public Boolean isAdmin {get; set;}
        @AuraEnabled
        public Boolean canApproveBudget {get; set;}
    }
}