force-app/main/default/objects/National_Outings_Country__mdt/National_Outings_Country__mdt.object-meta.xml
<CustomObject>
    <label>National Outings Country</label>
    <pluralLabel>National Outings Countries</pluralLabel>
</CustomObject>

force-app/main/default/objects/National_Outings_State__mdt/National_Outings_State__mdt.object-meta.xml
<CustomObject>
    <label>National Outings State</label>
    <pluralLabel>National Outings States</pluralLabel>
</CustomObject>

force-app/main/default/objects/National_Outings_State__mdt/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <label>Code</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/National_Outings_Subcommittee_Values__mdt/National_Outings_Subcommittee_Values__mdt.object-meta.xml
<CustomObject>
    <label>National Outings Subcommittee_Values</label>
    <pluralLabel>National Outings Subcommittee_Values</pluralLabel>
</CustomObject>

force-app/main/default/objects/National_Outings_Trip_Type_Values__mdt/National_Outings_Trip_Type_Values__mdt.object-meta.xml
<CustomObject>
    <label>National Outings Trip Type Values</label>
    <pluralLabel>National Outings Trip Type Values</pluralLabel>
</CustomObject>

force-app/main/default/objects/National_Outings_Vendor_Type__mdt/National_Outings_Vendor_Type__mdt.object-meta.xml
<CustomObject>
    <label>National Outings Vendor Type</label>
    <pluralLabel>National Outings Vendor Types</pluralLabel>
</CustomObject>

force-app/main/default/objects/National_Outings_Vendor_Type__mdt/fields/Domestic__c.field-meta.xml
<CustomField>
    <fullName>Domestic__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Domestic</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/National_Outings_Vendor_Type__mdt/fields/International__c.field-meta.xml
<CustomField>
    <fullName>International__c</fullName>
    <defaultValue>false</defaultValue>
    <label>International</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/NatoutTripOptions.cls
public with sharing class NatoutTripOptions {
    @AuraEnabled (cacheable=true)
    public static TripOptions getOptions() {
        TripOptions tripOptions = new TripOptions();
        
        List<National_Outings_Subcommittee_Values__mdt> subCommValues = [
            SELECT Label
            FROM National_Outings_Subcommittee_Values__mdt
            ORDER BY Label
        ];
        for(National_Outings_Subcommittee_Values__mdt option : subCommValues) {
            tripOptions.subcommList.add(option.Label);
        }

        List<National_Outings_Trip_Type_Values__mdt> tripTypeValues = [
            SELECT Label
            FROM National_Outings_Trip_Type_Values__mdt
            ORDER BY Label
        ];
        for(National_Outings_Trip_Type_Values__mdt option : tripTypeValues) {
            tripOptions.tripTypeList.add(option.Label);
        }

        List<National_Outings_Country__mdt> countryValues = [
            SELECT Label
            FROM National_Outings_Country__mdt
            ORDER BY Label
        ];
        for(National_Outings_Country__mdt option : countryValues) {
            tripOptions.countryList.add(option.Label);
        }

        tripOptions.stateList = getStateOptions();        

        return tripOptions;
    }
    @AuraEnabled (cacheable=true)
    public static VendorOptions getVendorOptions() {
        List<National_Outings_Vendor_Type__mdt> typeList = [
            SELECT Label, Domestic__c, International__c
            FROM National_Outings_Vendor_Type__mdt
            ORDER BY Label
        ];
        VendorOptions opts = new VendorOptions();
        for(National_Outings_Vendor_Type__mdt vend : typeList) {
            if(vend.Domestic__c) {
                opts.domesticList.add(vend.Label);
            }
            if(vend.International__c) {
                opts.internationalList.add(vend.Label);
            }
        }
        return opts;
    }
    public static List<LabelValue> getStateOptions() {
        List<LabelValue> stateList = new List<LabelValue>();
        for(National_Outings_State__mdt state : 
            [
                SELECT Label, Code__c
                FROM National_Outings_State__mdt
                ORDER BY Label
            ]) {
                stateList.add(new LabelValue(state.Label, state.Code__c));
            }
        return stateList;
    }
    public class TripOptions {
        @AuraEnabled
        public List<String> subcommList = new List<String>();
        @AuraEnabled
        public List<String> tripTypeList = new List<String>();
        @AuraEnabled
        public List<String> countryList = new List<String>();
        @AuraEnabled
        public List<LabelValue> stateList = new List<LabelValue>();
    }
    public class VendorOptions {
        @AuraEnabled
        public List<String> domesticList = new List<String>();
        @AuraEnabled
        public List<String> internationalList = new List<String>();
    }
    public class LabelValue {
        public LabelValue(String label, String value) {
            this.label = label;
            this.value = value;
        }
        @AuraEnabled
        public String label {get; set;}
        @AuraEnabled
        public String value {get; set;}
    }
}